### PR TITLE
fix(fesom-2.0.yaml): missing destination

### PR DESCRIPTION
**Pull request by pgierz**
@christian-stepanek's bugfix for #582

#bump (@mandresm: is that the correct way?)

### CODE REVIEW

**Comment by mandresm** [comment]
Correct

**Review by mandresm — APPROVED** [review]

**Comment by pgierz** [comment]
...now we wait for the robot magic 🪄 fingers crossed

**Comment by pgierz** [comment]
Wait I think it is set up to need to be in a comment, so:

#bump

**Comment by mandresm** [comment]
Is not working probably because it needs to be a comment, not a PR description. Give it a try as a comment if you will

**Comment by mandresm** [comment]
Oh, it actually did somerthing, it's alive!

**Comment by pgierz** [comment]
Cool 👍🏻

**Pull request merged**
