### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by nwieters**
This pull request adds a github-actions workflow to set inactive issues (older than 365 days, this is for a first test and can be decreased later) to 'Stale'. The following steps are done:

- the issue will be labelled with 'Stale'
- a comment will be added to the issue
- and if no further changes will be done to the issue, it will be closed after 30 days.

### CODE REVIEW

**Review by pgierz — APPROVED** [review]
This looks exactly like what we talked about, excellent!! Does it also work on things that are already online retroactively? That would unfortunately still be a step to be done "by hand", but we can live with that. 

There is no really nice way to test that particular problem unless we open something ourselves and then just wait, and I think we all have better uses for our time ;-)

**Comment by nwieters** [comment]
Thanks @pgierz ,
let's see what happens tomorrow at 14:00. I hope that it will do this retroactive. If not I will reduce the time until it is marked as stale to something shorter.

**Comment by nwieters** [comment]
#bump

**Comment by mandresm** [comment]
Interesting... What about enhancement issues? Those should stay until we have time to take care of them.

**Pull request merged**
