### PR TITLE
Fix/git detached head

### LINKED ISSUE #734: git feature #690 broken
It seems to me that the git version feature #690 is not quite working.
After merging release into my current test branch in oder to get the latest levante flags, I recompiled awicm3-v3.1 on levante and tried to run a basic runscript (`/runscripts/awicm3/v3.1/awicm3-v3.1-levante-TCO95L91-CORE2_initial.yaml`)

I get:

```
Traceback (most recent call last):
  File "/home/a/a270092/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270092/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepcompute.py", line 36, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 61, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270092/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepare.py", line 702, in add_vcs_info
    vcs_versions[model] = helpers.get_all_git_info(model_dir)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 422, in get_all_git_info
    "branch_name": get_git_branch(path),
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 375, in get_git_branch
    return repo.head.reference.name
  File "/home/a/a270092/.local/lib/python3.9/site-packages/git/refs/symbolic.py", line 294, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'e48c9f09ff85aaf7ccb4e20d84e06887eb99d824'
```

Some of my git "branches" are tags. Maybe this is tripping up the system?

### PR DESCRIPTION
**Pull request by pgierz**
Should fix the broken git branch stuff with detached head, sorry about that.

### CODE REVIEW

**Comment by pgierz** [comment]
There is probably a better way to do this, but my brain is fried today. Someone please double check.

**Comment by mandresm** [comment]
Some models are still broken in the tests. I'll review this tomorrow and maybe even have a look at the models having problems (AWICM3)

**Comment by pgierz** [comment]
As with the doc-test branch, all failing tests are now from `esm-tests`, and all seem to be "Run Files Differ"

**Review by mandresm — APPROVED** [review]

**Comment by mandresm** [comment]
#bump

**Comment by pgierz** [comment]
Will close #734, still needs some manual testing

**Comment by pgierz** [comment]
Manually tested with AWICM3 frontiers-xios and AWICM3 3.1.

@JanStreffing: something is still weird. But if you are happy with this, then that is how it shall be. Currently `xios` does not seem to have a model directory, and `rnfmap` is not a git-controlled thing.:
```shell
$ cat ../experiments/git_test_001/run_20000101-20011231/log/git_test_001_vcs_info.yaml
```
```yaml

esm_tools: d3e90a56
fesom:
  branch_name: awicm-3-frontiers_parallel-restart
  diffs:
  - ''
  hash: 9b27593c
  path: /work/ab0995/a270077/SciComp/Model_Support/AWICM3/broken_git_check/model_codes/awicm3-frontiers-xios///fesom-2.0
oasis3mct:
  branch_name: awicm-3-frontiers
  diffs:
  - ''
  hash: 347e788
  path: /work/ab0995/a270077/SciComp/Model_Support/AWICM3/broken_git_check/model_codes/awicm3-frontiers-xios///oasis
oifs:
  branch_name: awicm-3-frontiers-xios
  diffs:
  - diff --git a/src/ifs/module/yommcc.F90 b/src/ifs/module/yommcc.F90
  - index e7d74a1..131227a 100644
  - '--- a/src/ifs/module/yommcc.F90'
  - +++ b/src/ifs/module/yommcc.F90
  - '@@ -180,7 +180,7 @@ INTEGER(KIND=JPIM) :: NFRCPL'
  - ' '
  - ' !Logical switches for Coupling'
  - ' LOGICAL :: COUPLENEMOECE = .FALSE.   ! Use EC-Earth NEMO coupling'
  - '-LOGICAL :: COUPLEFESOM2 = .FALSE.    ! Use AWI FESOM2 coupling'
  - '+LOGICAL :: COUPLEFESOM2 = .TRUE.    ! Use AWI FESOM2 coupling'
  - ' LOGICAL :: COUPLENEMOFOCI = .FALSE.   ! Use FOCI NEMO coupling'
  - ' LOGICAL :: LNEMOLIMGET = .FALSE.   ! Get new fields'
  - ' LOGICAL :: LNEMOLIMPUT = .FALSE.   ! Put new fields'
  hash: c78fa46
  path: /work/ab0995/a270077/SciComp/Model_Support/AWICM3/broken_git_check/model_codes/awicm3-frontiers-xios///oifs-43r3
rnfmap: Not a git-controlled model!
xios: Unable to locate model_dir for xios.
```

...and, yes, I am not particularly happy that `diffs` is a list of strings. I might still change that.

**Comment by JanStreffing** [comment]
Not sure why it's saying rnfmap is not a git controlled thing. It certainly is: 
`https://gitlab.dkrz.de/ec-earth/runoff-mapper`
XIOS seems to use the model_dir from awicm3 and  `install_bins: bin/xios.x`
No harm in adding a model_dir for consistencies sake I guess. Though it seems required to run the model.

**Comment by pgierz** [comment]
Jan, have a look in `levante: /work/ab0995/a270077/SciComp/Model_Support/AWICM3/broken_git_check/model_codes/awicm3-frontiers-xios`

It might be that the `install_bins` part is generating folders for things that aren't git repos (or at least, are not git repos where the `model_dir` is defined). That's too deep in the AWI-CM3 config for me to be comfortable touching it though...

**Comment by mandresm** [comment]
There seems to be a problem in `FOCI` (blogin):
```   Traceback (most recent call last):
    File "/github/home/.local/bin/esm_runscripts", line 11, in <module>
      load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')()
    File "/__w/esm_tools/esm_tools/src/esm_runscripts/cli.py", line 278, in main
      Setup()
    File "/__w/esm_tools/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
      self.prepcompute()
    File "/__w/esm_tools/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
      self.config = prepcompute.run_job(self.config)
    File "/__w/esm_tools/esm_tools/src/esm_runscripts/prepcompute.py", line 36, in run_job
      config = evaluate(config, "prepcompute", "prepcompute_recipe")
    File "/__w/esm_tools/esm_tools/src/esm_runscripts/helpers.py", line 68, in evaluate
      config = esm_plugin_manager.work_through_recipe(
    File "/__w/esm_tools/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
      config = getattr(submodule, workitem)(config)
    File "/__w/esm_tools/esm_tools/src/esm_runscripts/prepare.py", line 707, in add_vcs_info
      if helpers.is_git_repo(model_dir):
    File "/__w/esm_tools/esm_tools/src/esm_runscripts/helpers.py", line 329, in is_git_repo
      git.Repo(path).git_dir
    File "/github/home/.local/lib/python3.8/site-packages/git/repo/base.py", line 152, in __init__
      raise NoSuchPathError(epath)
  git.exc.NoSuchPathError: /__w/esm_tools/esm_tools/src/esm_tests/resources/automatic_testing/comp/focioifs/focioifs-2.0/oifs-43r3
  Copying standard yamls from:  /__w/esm_tools/esm_tools/configs/
  Copying standard namelists from:  /__w/esm_tools/esm_tools/namelists/
  /__w/esm_tools/esm_tools/src/esm_tests/resources/runscripts/focioifs/focioifs-piCtl-test_lowcpu.yaml
  ```
  Do you want me to try to reproduce it in a real computer?

**Comment by pgierz** [comment]
No, that's something else, and actually is still a bug in the git part. I'll look after I do the pool stuff.

**Comment by pgierz** [comment]
Broken tests are at this point "wrong truth". The technical elements seem to working fine. The error reported by @mandresm is now fixed. I am not 100% sure if my fix is the best way of doing it.

The offending function checks: is this a git directory? You get `True` if it is a git dir (makes sense), and you get `False` if it is not (make sense) OR `False` if it is non-existent (this part I am not sure about). Throwing the FileNotFound error might be better here, but that kills our tests. That FileNotFound case only happens on CI; so it will never be a problem in real production.

In any case, I would vote: please merge. :-)

**Comment by mandresm** [comment]
> The offending function checks: is this a git directory? You get `True` if it is a git dir (makes sense), and you get `False` if it is not (make sense) OR `False` if it is non-existent (this part I am not sure about). Throwing the FileNotFound error might be better here, but that kills our tests. That FileNotFound case only happens on CI; so it will never be a problem in real production.

Agreed, this is the sort of thing that is going to be tested in the actual `esm_tests`, and we have to run those from time to time anyway, so I think it's okay if it doesn't work for check tests.

**Review by mandresm — APPROVED** [review]
Great feature, thanks for fixing it! :)

**Comment by mandresm** [comment]
updating the truth...

**Comment by mandresm** [comment]
All tests passed (except AWIESM icebergs due to lack of update related to an ongoing issue), #bump!

**Pull request merged**
