### PR TITLE
derive freshwater flux from thickness change and not mass balance

### PR DESCRIPTION
**Pull request by ackerlar**

### CODE REVIEW

**Comment by mandresm** [comment]
Hey @ackerlar, can this be merged? If so I'll do the review and look at the tests and merge it after that. I am aware that #1200 contain these changes.

**Comment by ackerlar** [comment]
Hi @mandresm , yes it can be merged!

**Comment by mandresm** [comment]
#approve-changes

**Review by mandresm — APPROVED** [review]

**Comment by mandresm** [comment]
#bump

**Pull request merged**
