### PR TITLE
clean: remove all references to six

### PR DESCRIPTION
**Pull request by pgierz**
As we do not support `Python 2.x`, the `six` package is redundant; and led to different ways of writing simple things like print statements and dictionary iteration. This PR removes all instances of `six`.

### CODE REVIEW

**Comment by pgierz** [comment]
The tests are failing with:
```
File "/__w/esm_tools/esm_tools/src/esm_master/esm_master.py", line 55, in main_flow
[965](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:966)
    complete_setup = SimulationSetup(user_config=user_config)
[966](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:967)
  File "/__w/esm_tools/esm_tools/src/esm_runscripts/sim_objects.py", line 42, in __init__
[967](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:968)
    self.config = prepare.run_job(self.config)
[968](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:969)
  File "/__w/esm_tools/esm_tools/src/esm_runscripts/prepare.py", line 17, in run_job
[969](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:970)
    helpers.evaluate(config, "prepare", "prepare_recipe")
[970](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:971)
  File "/__w/esm_tools/esm_tools/src/esm_runscripts/helpers.py", line 68, in evaluate
[971](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:972)
    config = esm_plugin_manager.work_through_recipe(
[972](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:973)
  File "/__w/esm_tools/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
[973](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:974)
    config = getattr(submodule, workitem)(config)
[974](https://github.com/esm-tools/esm_tools/runs/7606031549?check_suite_focus=true#step:10:975)
AttributeError: module 'esm_runscripts.batch_system' has no attribute 'find_openmp'
```

~That looks unrelated to the changes I made here, but I cannot tell. Was `find_openmp` a third-party plugin?~

EDIT: it's definitely there:
`src/esm_runscripts/batch_system.py:627:    def find_openmp(config):`

**Comment by pgierz** [comment]
Also interesting: locally running `esm_tests -necus False` on Ollie has at least my AWIESM tests behaving:
```
	COMPILING (4.8%) awiesm-2.1-recom
		Directory already exists, skipping
		'comp/awiesm/awiesm-2.1-recom//comp-echam-6.3.05p2-wiso_script.sh' files are identical
		'comp/awiesm/awiesm-2.1-recom//comp-fesom-2.1-recom_script.sh' files are identical
		'comp/awiesm/awiesm-2.1-recom//comp-oasis3mct-2.8-paleodyn_script.sh' files are identical
		Success!
		
	COMPILING (9.5%) awiesm-2.1
		Directory already exists, skipping
		'comp/awiesm/awiesm-2.1//comp-oasis3mct-2.8-paleodyn_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-echam-6.3.05p2-awiesm-2.1_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-fesom-2.1-awiesm-2.1_script.sh' files are identical
		Success!
		
	COMPILING (14.3%) awiesm-2.1-wiso
		Directory already exists, skipping
		'comp/awiesm/awiesm-2.1-wiso//comp-oasis3mct-2.8-paleodyn_script.sh' files are identical
		'comp/awiesm/awiesm-2.1-wiso//comp-fesom-2.1-wiso_script.sh' files are identical
		'comp/awiesm/awiesm-2.1-wiso//comp-echam-6.3.05p2-wiso_script.sh' files are identical
		Success!
		
	COMPILING (19.0%) awiesm-2.1
		Directory already exists, skipping
		'comp/awiesm/awiesm-2.1//comp-oasis3mct-2.8-paleodyn_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-echam-6.3.05p2-awiesm-2.1_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-fesom-2.1-awiesm-2.1_script.sh' files are identical
		Success!
		
	COMPILING (23.8%) awiesm-2.1
		Directory already exists, skipping
		'comp/awiesm/awiesm-2.1//comp-oasis3mct-2.8-paleodyn_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-echam-6.3.05p2-awiesm-2.1_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-fesom-2.1-awiesm-2.1_script.sh' files are identical
		Success!
		
	COMPILING (28.6%) awiesm-2.1
		Directory already exists, skipping
		'comp/awiesm/awiesm-2.1//comp-oasis3mct-2.8-paleodyn_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-echam-6.3.05p2-awiesm-2.1_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-fesom-2.1-awiesm-2.1_script.sh' files are identical
		Success!
		
	COMPILING (33.3%) awiesm-2.1
		Directory already exists, skipping
		'comp/awiesm/awiesm-2.1//comp-oasis3mct-2.8-paleodyn_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-echam-6.3.05p2-awiesm-2.1_script.sh' files are identical
		'comp/awiesm/awiesm-2.1//comp-fesom-2.1-awiesm-2.1_script.sh' files are identical
		Success!
```

**Comment by mandresm** [comment]
This is indeed a problem, also when you run actual simulations. I'll be pushing a fix soon.

**Comment by pgierz** [comment]
OK, that may be indicative of a deeper problem. Part of my cleanup also removed any un-used imports, and batch system is never used in prepexp except for just importing it so that it is available...

**Comment by mandresm** [comment]
Agreed... I think it is related to the fact that `find_openmp` is a method inside the class `batch_system`, so even if `batch_system` module is imported in `prepare.py`, the method `find_openmp` is not reached in the `esm_plugin_manager`, because you need `from .batch_system import batch_system` (from module import class). Definitely, in the wrong place, but I'm cannot look for a better solution now, and this is probably something to better be done through the cleaning up.

**Review by mandresm — APPROVED** [review]
The only left errors in `esm_tests` are related to a previously merged PR where the truth was not updated.

**Comment by pgierz** [comment]
#bump

**Pull request merged**
