### PR TITLE
documentation update for retrieving the esm_tools version

### PR DESCRIPTION
**Pull request by mandresm**
Update to the versions documentation (requested by @mbutzin).

https://esm-tools.readthedocs.io/en/docs-get_version/esm_versions.html

### CODE REVIEW

**Review by pgierz — APPROVED** [review]
Yes! Sorry, I should have done this myself.

**Comment by pgierz** [comment]
#bump #approve-changes

**Comment by mandresm** [comment]
Approve changes is only needed when tests differ and someone has reviewed the changes. I thought we said we won't bump version for docs, but not really a big issue. All this just tells me the documentation of `esm_tests` is kind of urgent XD

**Comment by pgierz** [comment]
We should not bump for docs, sorry. That was just a gut instinct of "things to do on a PR"

**Pull request merged**
