### PR TITLE
484 error handeling in case of empty yaml block

### LINKED ISSUE #484: Error handeling in case of empty yaml block.
This error handling was a bit confusing while setting up oifsamip setup.
I erroneously added an empty block for the amip component to my first runscript, thinking that it would be good to show other users that the possibility to add custom amip options exists. Even though I did not have any right now. 
```
amip:

```
This is not correct yaml syntax. However instead of getting an error about wrong yaml syntax, I got one about `user_config["general"]["setup_name"] ` does not exist

```
(Pdb) c
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 1: general:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 4: general:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 5: user:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 6: setup_name:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 7: version:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 8: compute_time:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 9: initial_date:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 10: final_date:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 11: /work/ollie/${user}/runtime/${general.setup_name}-${general.version}/: bad substitution
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 12: nday:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 13: nmonth:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 14: nyear:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 16: computer:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 17: heterogeneous_parallelization:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 19: oifsamip:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 20: postprocessing:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 21: /home/ollie/${user}/model_codes/${general.setup_name}-${general.version}/: bad substitution
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 23: amip:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 25: oifs:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 26: resolution:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 27: levels:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 28: prepifs_expid:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 29: input_expid:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 30: wam:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 31: lresume:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 32: time_step:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 33: nproc:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 34: omp_num_threads:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 36: oasis3mct:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 37: lresume:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 38: time_step:: command not found
Traceback (most recent call last):
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/ollie/jstreffi/.local/bin/esm_runscripts", line 3, in <module>
    import re
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/cli.py", line 221, in main
    Setup = SimulationSetup(command_line_config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 31, in __init__
    self.get_total_config_from_user_config(user_config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 153, in get_total_config_from_user_config
    setup_name = user_config["general"]["setup_name"]
KeyError: 'setup_name'
```

The fix was simple, just remove the block or add something into it, but I do think that more people unfamiliar with yaml might stumble over this.

### PR DESCRIPTION
**Pull request by nwieters**
Closes #484

### CODE REVIEW

**Comment by nwieters** [comment]
If there is an empty component in the user runscript:
`amip:`
or
`amip: ""`
the entry for this components in the `user_config` dictionary will be set to an empty dictionary.
`user_config[model] = {}`

and a `user_note` will be displayed to stdout:

```
Warning: YAML syntax
--------------------
The component amip in your configuration file /work/ab0995/a270089/runtime/awicm3-v3.1/run_issue_484_001/scripts/awicm3-v3.1-levante-TCO95L91-CORE2_initial_issue_484.yaml is empty. No further variables are set for this component in your runscript.
```

**Comment by nwieters** [comment]
Is there a way to prevent the `user_note` to be displayed twice?
I tried `isinteractive` but this is not available there.

Besides setting `user_config[model] = {}` I though about removing it from `user_config`: 
`del user_config[model]`

What do you think is the better option?

**Review by pgierz — APPROVED** [review]
Looks good! Can go in :-)

**Comment by pgierz** [comment]
> Is there a way to prevent the `user_note` to be displayed twice? I tried `isinteractive` but this is not available there.

You would need to cache all the warnings and notes and dump them all at the same time to cleanly do that. Don't build that.

> 
> Besides setting `user_config[model] = {}` I though about removing it from `user_config`: `del user_config[model]`
> 
> What do you think is the better option?

I would rather throw it away. Then we at least get `KerError` instead of something else that goes bad down the chain.

**Comment by nwieters** [comment]
Thank you @pgierz .

I now remove the empty components from `user_config`.

This is done before all other config files are merged in. 
If you set for example:
`oasis3mct:`
in the runscript, it will be removed before the oasis configuration will be merged to `user_config`.

**Review by mandresm — APPROVED** [review]
It works well, and I'm okay with having a duplication here. I was looking at the code changes that would be needed to avoid the duplication of the warning and I don't think they are worth the time. Ideally this warning will be there for brief time, then people will fix their yaml files and then they won't need to see the double warning anymore.

**Comment by mandresm** [comment]
#bump

**Pull request merged**
