### PR TITLE
Standalone Fesom 2.6 in esm_tools

### PR DESCRIPTION
**Pull request by JanStreffing**

### CODE REVIEW

**Comment by JanStreffing** [comment]
Also adding @ogures

**Comment by JanStreffing** [comment]
Please add what might be needed for RECOM and Iceberg/WISO

**Comment by chrisdane** [comment]
The files look good. Did you compile and/or made a 1-year test run with the esm_tools? This is covered by the automated tests I guess?

**Comment by JanStreffing** [comment]
> The files look good. Did you compile and/or made a 1-year test run with the esm_tools? This is covered by the automated tests I guess?

I did, yes.

**Review by ackerlar — APPROVED** [review]
Works for me!

**Comment by pgierz** [comment]
#bump

**Comment by mandresm** [comment]
Can some of you share a standalone runscript that works for fesom-2.6 so that I can add it to the tests?

**Comment by mandresm** [comment]
okay, forget about it, I have just seen that there is a runscript in the PR itself, I'll give it a go!

**Pull request merged**
