### PR TITLE
fix/repeated git clones

### PR DESCRIPTION
**Pull request by mandresm**
fix a bug where repeated git commands were allowed in esm_master (#1236)

### CODE REVIEW

**Review by pgierz — APPROVED** [review]
👍🏻

**Comment by mandresm** [comment]
I am fixing the problems with the test container

**Comment by pgierz** [comment]
Hm, odd. 404 when installing `jq`? What do we use `jq` for? I thought the apt server was down, but forcing a rerun doesn't resolve the problem.

I haven't looked at the test container in a very long time. Try switching to use just a regular Ubuntu...? I am not sure why we are using a custom one anyway. If we want to mimic the HPC more closely, we could use a Rocky Linux container.

**Comment by mandresm** [comment]
Merging from release with the CI fixed

**Comment by mandresm** [comment]
#bump !!!!!!

**Pull request merged**
