### PR TITLE
Hotfix: adding the copy of xml files I wanted to avoid. for now

### PR DESCRIPTION
**Pull request by JanStreffing**
Until a better solution is found i.e. modifying xml files. This is the way we need to go...

### CODE REVIEW

**Comment by JanStreffing** [comment]
Doing one quick testrun.

**Comment by JanStreffing** [comment]
Works, I found the model is very slow, but also without the changes, either a separate issue or hardware. But this fix
 should go in as is.

Probably hardware, seeing as the timestep length varies from 3.8 to 16.6 seconds:

 ```
15:23:48 0AAA00AAA STEPO       13     8.453    8.453   11.703      2:10      3:22 0.11421017060395E-04       0GB       0MB
 15:23:57 0AAA00AAA STEPO       14     6.469    6.469    8.831      2:16      3:31 0.11381499809790E-04       0GB       0MB
 15:24:06 0AAA00AAA STEPO       15     5.772    5.772    8.775      2:22      3:40 0.11341959445009E-04       0GB       0MB
 15:24:16 0AAA00AAA STEPO       16     7.946    7.946   10.473      2:30      3:50 0.11330224280876E-04       0GB       0MB
 15:24:44 0AAA00AAA STEPO       17    15.131   15.131   27.160      2:45      4:18 0.11328832504553E-04       0GB       0MB
 15:25:12 A00000000 STEPO       18    16.611   16.611   28.056      3:02      4:46 0.11322402704131E-04       0GB       0MB
15:25:34 0AAA00AAA STEPO       19    11.762   11.762   18.514      3:16      5:08 0.11307759107439E-04       0GB       0MB
 15:25:43 0AAA00AAA STEPO       20     6.729    6.729    9.166      3:23      5:17 0.11297615041120E-04       0GB       0MB
 15:25:55 0AAA00AAA STEPO       21     8.102    8.102   12.098      3:31      5:29 0.11280364596331E-04       0GB       0MB
 15:25:57 0AAA00AAA STEPO       22     4.994    4.994    1.790      3:36      5:31 0.11253915722434E-04       0GB       0MB
 15:25:58 0AAA00AAA STEPO       23     3.821    3.821    1.279      3:40      5:32 0.11218646494724E-04       0GB       0MB
```

**Comment by JanStreffing** [comment]
Would be great to have this merged asap.

**Review by mandresm — APPROVED** [review]

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#bump

**Comment by JanStreffing** [comment]
ty!

**Pull request merged**
