### PR TITLE
fix/esm_master destination can be nested directories

### PR DESCRIPTION
**Pull request by mandresm**
(cherry picked from commit 5c686db4657d8a4ec018c80bedc7646d22458ced)

adds possibility to have destination be a nested directory for esm_master

### CODE REVIEW

**Comment by mandresm** [comment]
closes #1248

**Review by pgierz — APPROVED** [review]

**Comment by pgierz** [comment]
#bump

**Comment by mandresm** [comment]
this was not ready to merge and it's broken. I am reverting the merge with push force on `release` and reopening this PR

**Comment by mandresm** [comment]
also, please make sure that esm_tests that are not `albedo` or `blogin` pass. If `levante`, `aleph` or `juwels` are not passing we should not be merging

**Comment by mandresm** [comment]
okay, I'm not going to push-force to release, but instead make a new PR, so that we don't destroy anyone's work accidentally

**Pull request merged**
