### PR TITLE
Juwels stages 2020

### PR DESCRIPTION
**Pull request by JanStreffing**
@mandresm What should the target of this merge be? Do we have some kind of intermediate between feature branch and release?  Can we do a CI test on these changes, or should I test them locally?

### CODE REVIEW

**Comment by mandresm** [comment]
I think making it be release it's okay, since this should be fixing Juwels and therefore it's a hotfix. I'm triggering the GEOMAR and AWICM3 tests in Juwels now.

**Comment by seb-wahl** [comment]
Fine with me.

**Comment by pgierz** [comment]
I read CI and perked up my ears: what needs auto-testing? The changes seem to be specific to Juwels, so until we get a dummy account there for automatic tests, I don't foresee changing anything. Given the turnaround time of Juwels support, I don't really see a dummy account arriving anytime soon...

**Comment by mandresm** [comment]
> I read CI and perked up my ears: what needs auto-testing? The changes seem to be specific to Juwels, so until we get a dummy account there for automatic tests, I don't foresee changing anything. Given the turnaround time of Juwels support, I don't really see a dummy account arriving anytime soon...

I think Jan means by CI the `esm_tests` testing tool. It's not CI, but is just one command from compiling and running a bunch of runscripts.

**Comment by mandresm** [comment]
> I read CI and perked up my ears: what needs auto-testing? The changes seem to be specific to Juwels, so until we get a dummy account there for automatic tests, I don't foresee changing anything. Given the turnaround time of Juwels support, I don't really see a dummy account arriving anytime soon...

**Comment by mandresm** [comment]
Sorry for closing it, there is something wrong with me this year...

**Comment by pgierz** [comment]
@mandresm: We should take an afternoon and put my CI and your tests all in the same box. Next week sometime? 

And no worries: I would guess most of us aren't all the way there this year yet ;-)

**Comment by mandresm** [comment]
> @mandresm: We should take an afternoon and put my CI and your tests all in the same box. Next week sometime?

Sure, but can it be in two weeks? I still need to do a couple of extra things in the `esm_tests` packages to be usable by anyone.

**Comment by pgierz** [comment]
There is still one pending test (or, I guess in progress), which will likely fail due to the problems related to #533. If that is the only thing failing, I give my OK. And I will try to sort out the failing tests soon...

**Comment by mandresm** [comment]
This will be merged in #574 and therefore I close this PR

**Pull request closed without merging**
