### PR TITLE
using different name for main on smhi and the main on dkrz,...

### PR DESCRIPTION
**Pull request by JanStreffing**
... thus allowing for easy mergeing and no rebasing

I renamed the default branch of openifs in our new repo on dkrz which is a second remote of my fork off of the smhi vendor. By using a different name for the main branch, I can have both the main branch that is in sync with the EC-Earth vendor/main, and our own main branch with additional merges in the same repo.

Anything happening on smhi/vendor/main can be added to dkrz/main_dkrz via simple merge request. Our features merges into main_dkrz I need to turn into patches and apply them to branches off of main. Then I can push them to my fork on smhi, and create a clean MR into smhi/vendor/main from there.

Just though I'd write that down here while it's fresh in my mind. Probably to add to documentation later.

### CODE REVIEW

**Review by mandresm — APPROVED** [review]

**Comment by mandresm** [comment]
#approve-changes

**Comment by JanStreffing** [comment]
The failed tests fail for the right reason. The change made it into the final yaml ;-)

**Comment by mandresm** [comment]
#bump

**Comment by mandresm** [comment]
#approve-changes

**Pull request merged**
