### PR TITLE
Fix/rnfmap names

### LINKED ISSUE #871: AWI-CM3-master not finding orbital forcing namelists
With the implementation of the new ECE4 code for AWI-CM3, activating the orbital forcing code in the transcript leads to the model not being able to find such namelist.

When comparing `AWI-CM3-master` and `AWI-CM3-v3.1` `fort.4`, one sees that both miss the `NAMORB` section. So this should not be the main issue, as just by `add_namelist_changes` in the runscript, it worked for `AWI-CM3-v3.1`. 

Now when one looks at the location of the namelist and source code:

**AWI-CM3-master**
namorb.h:`oifs-43/src/ecearth/orbital/`
yomorb.F90:`oifs-43/src/ecearth/orbital/`

**AWI-CM3-v3.1**
namorb.h:`oifs-43r3/src/ifs/namelist/`
yomorb.F90:`oifs-43r3/ifs/module/`
**To Reproduce**

I tried to change the location of these files on `AWI-CM3-master` and recompiled the model to see whether the namelists would be found. However, it led to the same error.

 - Supercomputer: juwels
 - Version release - 6.18.0
 - Models' folder - `/p/project/chhb20/fmatos/runtime/awicm3-master/model_codes`
 - Runscript - `/p/project/chhb20/fmatos/runtime/awicm3-master/runscript_testing/pi_orb_forcing.yaml`
 - Log with error described: `/p/project/chhb20/fmatos/runtime/awicm3-master/runscript_testing/pi_orbforc_005_c.log`

**Additional context**
In the runscript, the section for NAERAD also led to the same error, but this module refers to the GHG concentrations, and the implementation of it is still being discussed for the future.

### PR DESCRIPTION
**Pull request by JanStreffing**
fixes https://github.com/esm-tools/esm_tools/issues/871

### CODE REVIEW

**Review by mandresm — APPROVED** [review]

**Comment by mandresm** [comment]
#bump

**Comment by fernandadialzira** [comment]
What is this section on the example namelist for, @JanStreffing:
```
add_namelist_changes:
        fort.4:
            NAMCLDP:
                SCLCT_SWITCH: 2
```

**Comment by JanStreffing** [comment]
Hello Fernanda, this turns on the sw rad changes from: https://www.ecmwf.int/sites/default/files/elibrary/2016/17261-reducing-systematic-errors-cold-air-outbreaks.pdf

This was always on by default for v3.0 and v3.1, but has only recently been included in the master branch.

**Comment by JanStreffing** [comment]
sorry for the messy merge request that contained two things.

**Comment by fernandadialzira** [comment]
> Hello Fernanda, this turns on the sw rad changes from: https://www.ecmwf.int/sites/default/files/elibrary/2016/17261-reducing-systematic-errors-cold-air-outbreaks.pdf
> 
> This was always on by default for v3.0 and v3.1, but has only recently been included in the master branch.

Ok! Thank you! I have started some paleo simulations without turning it on, but I will do that for the future.

**Pull request merged**
