### PR TITLE
ci: test test test

### PR DESCRIPTION
**Pull request by pgierz**
ignore this PR please

EDIT

Do NOT ignore this PR please :-)

Automatic tests for everything under `tests` now works. Doctests would work too, but some examples will not be complete. You can mark them with `# doctest: +SKIP`

### CODE REVIEW

**Comment by pgierz** [comment]
@mandresm, can you add whatever magic you need to do to get the ollie test to work directly to this branch?

**Comment by mandresm** [comment]
Yes, I'll do that right away.

**Review by mandresm — APPROVED** [review]
All looks good to me, and now all tests pass

**Comment by pgierz** [comment]
...what? No new commit? I am confused, but whatever. We can now use the big green checkmark in the future :-)

**Comment by mandresm** [comment]
The commit was on the truth repository, it's a submodule ;)

**Pull request merged**
