### PR TITLE
Hotfix/fesom newday

### PR DESCRIPTION
**Pull request by mandresm**
Same as #426

### CODE REVIEW

**Comment by pgierz** [comment]
We had failing tests on the version bump, is that a problem? (Note the big red X)

**Comment by mandresm** [comment]
Yeah, the problems in `prep_release` is that `esm_runscripts` is not in `prep_release` while `esm_tools` is. We need to come up with an idea on how to coordinate different versions packages with different branches for the testing.

**Comment by pgierz** [comment]
....just one repo? Instead of 5? Just an idea 😉

**Comment by mandresm** [comment]
Yeah, I'm not opposed to that idea, I just don't see it happening before release 6 cause there is so much left to be done. In any case, why were the packages separated on the first place? (I was not there when it happened)

**Comment by pgierz** [comment]
That is a question Dirk can answer better than I can. We at the beginning wanted to (I guess) make very separate tools that could be used without depending on each other, but that is (at least as it is right now) no longer the case.

**Pull request merged**
