### PR TITLE
Monorepo awiesm wiso recom

### PR DESCRIPTION
**Pull request by mandresm**

### CODE REVIEW

**Comment by pgierz** [comment]
Sorry, there are too many changes for me to make sense of, so apologies for the dumb questions:

What is write env?

Why was it gone?

Why is it back?

**Comment by pgierz** [comment]
But also, hey, tests pass nothing is nuked. Hooray.

**Comment by mandresm** [comment]
> Sorry, there are too many changes for me to make sense of, so apologies for the dumb questions:
> 
> What is write env?
> 
> Why was it gone?
> 
> Why is it back?

It was gone with the workflow manager merge long time ago. `write_env` is an static method that writes only the environment of the `.sad` file into a single file, so that, OpenIFS preprocessing scripts can source that file. That's why it is back.

**Comment by mandresm** [comment]
RESULTS

- awicm:
    - 2.0:
        - awicm2-initial-monthly:
            - mistral:  compiles        runs
- awiesm:
    - 2.1-recom:
        - all_awiesm-2.1-recom:
            - mistral:  compiles        runs
    - 2.1-wiso:
        - PI_ctrl_awiesm-2.1-wiso:
            - mistral:  compiles        runs
- echam:
    - 6.3.04p1:
        - echam6.3.04p1-initial-monthly:
            - mistral:  compiles        runs
- fesom:
    - 2.0:
        - fesom2.0-initial-monthly:
            - mistral:  compiles        runs
    - 2.1:
        - fesom2.1-initial-monthly:
            - mistral:  compiles        runs

**Comment by mandresm** [comment]
All tests passed!

- awicm:
    - 2.0:
        - awicm2-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- awiesm:
    - 2.1-recom:
        - all_awiesm-2.1-recom:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
    - 2.1-wiso:
        - PI_ctrl_awiesm-2.1-wiso:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- echam:
    - 6.3.04p1:
        - echam6.3.04p1-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- fesom:
    - 2.0:
        - fesom2.0-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
    - 2.1:
        - fesom2.1-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- fesom-recom:
    - 1.4:
        - fesom-recom1.4-initial-daily:
            - ollie:    compiles        runs

**Comment by pgierz** [comment]
We really should get your test script to be part of the CI. Next time we are both at the institute on the same day (coming Tuesday, for example...?) let's make a mini hackathon out of it.

**Pull request merged**
