### PR TITLE
Awicm 3 frontiers xios

### PR DESCRIPTION
**Pull request by mandresm**

### CODE REVIEW

**Comment by JanStreffing** [comment]
Looks good.

**Review by JanStreffing — APPROVED** [review]
Looks good now

**Comment by mandresm** [comment]
- I'm done with the part of bringing back ollie's original environment and transferring the modifications to the `oifs.env.yaml`. I produce a `.run` script before my modifications and afterwards and compare them to make sure nothing has changed.
- I ran frontiers and `v3.0` compilations in `ollie`.
- Both `v3.0` and `frontiers` runs crashed on the 3rd step because they could not find `grib_set` on the preprocessing:
```
 Input dir: /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs// 
 Output dir: /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs// 
 InExp ID: awi3  
 OutExp ID: awi3  
 Start date: 20000103 
 End date:  
 Perturb: 0 
 New date: 20000102 
 Initial time: 2000-01-02T00:00:00 
 Start time: 2000-01-03T00:00:00 
 End time: 2021-12-15T00:00:00 
 
 * Change dataDate in files: 
  
/home/ollie/mandresm/esm_tools/configs/.//components/oifs/change_icm_date.sh: line 58: grib_set: command not found 
 Made new file:  /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs///ICMGGawi3INIT  with date  20000102
/home/ollie/mandresm/esm_tools/configs/.//components/oifs/change_icm_date.sh: line 70: grib_set: command not found 
 Made new file:  /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs///ICMGGawi3INIUA  with date  20000102
/home/ollie/mandresm/esm_tools/configs/.//components/oifs/change_icm_date.sh: line 116: grib_set: command not found 
 Made new file:  /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs///ICMSHawi3INIT  with date  20000102
/home/ollie/mandresm/esm_tools/configs/.//components/oifs/change_icm_date.sh: line 137: grib_set: command not found 
 Made new file:  /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs///cdwavein  with date  20000102
/home/ollie/mandresm/esm_tools/configs/.//components/oifs/change_icm_date.sh: line 137: grib_set: command not found 
 Made new file:  /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs///sfcwindin  with date  20000102
/home/ollie/mandresm/esm_tools/configs/.//components/oifs/change_icm_date.sh: line 137: grib_set: command not found 
 Made new file:  /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs///specwavein  with date  20000102
/home/ollie/mandresm/esm_tools/configs/.//components/oifs/change_icm_date.sh: line 137: grib_set: command not found 
 Made new file:  /work/ollie/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000103-20000103/input/oifs///uwavein  with date  20000102
 ```

**Comment by JanStreffing** [comment]
Does the path contain a correct path to a `grib_set` binary?

**Comment by mandresm** [comment]
EDIT: I don't know what variable is missing... This is the `env.sh` used:
```
module purge
module load cmake
module load udunits
module load gribapi/1.28.0
module unload intel.compiler
module load intel.compiler
module unload netcdf
module load hdf5
module load centoslibs cdo nco netcdf/4.6.2_intel
module load automake
module load python3/3.7.7_intel2020u2
module load git 
module list
module unload intel.mpi
module load intel.mpi
module unload gribapi
module unload gribapi

export LC_ALL=en_US.UTF-8
export FC="mpiifort -mkl"
export F77="mpiifort -mkl"
export MPIFC=mpiifort
export MPICC=mpiicc
export CC=mpiicc
export CXX=mpiicpc
export IO_LIB_ROOT=/work/ollie/jstreffi/software/HPC_libraries/intel2018.0.5_intelmpi_18.0.4_20210804
export HDF5ROOT=$IO_LIB_ROOT
export NETCDFFROOT=$IO_LIB_ROOT
export NETCDFROOT=$IO_LIB_ROOT
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_LIBRARIES=$NETCDFROOT/lib
export PERL5LIB=/usr/lib64/perl5
export LAPACK_LIB="-lmkl_intel_lp64 -lmkl_core -mkl=sequential -lpthread -lm -ldl"
export LAPACK_LIB_DEFAULT="-L/global/AWIsoft/intel/2018/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential"
export XML2ROOT=/usr
export ZLIBROOT=/usr
export MPIROOT=${I_MPI_ROOT}/intel64
export MPI_LIB=$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')
export PATH=/work/ollie/jhegewal/sw/cmake/bin:$PATH
export LD_LIBRARY_PATH=$IO_LIB_ROOT/lib:$LD_LIBRARY_PATH
export SZIPROOT=$IO_LIB_ROOT
export HDF5_ROOT=$HDF5ROOT
export ECCODESROOT=$IO_LIB_ROOT
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export OIFS_FFIXED=""
export GRIB_SAMPLES_PATH="$ECCODESROOT/share/eccodes/ifs_samples/grib1_mlgrib2"
export DR_HOOK_IGNORE_SIGNALS=-1
export OMP_SCHEDULE=STATIC
export OMP_STACKSIZE=128M
export ACCOUNT=None
export ESM_TESTING_DIR=/work/ollie/mandresm/testing//run/awicm3/
export MODEL_DIR=/work/ollie/mandresm/testing//comp/awicm3/awicm3-frontiers
export FESOM_USE_CPLNG="active"
export ECE_CPL_NEMO_LIM="false"
export ECE_CPL_FESOM_FESIM="true"
export ECE_AWI_CPL_FESOM="true"
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_MEM_PER_NODE
unset SLURM_MEM_PER_CPU
unset SLURM_DISTRIBUTION
unset SLURM_NTASKS
unset SLURM_NPROCS
unset SLURM_ARBITRARY_NODELIST
```

**Comment by mandresm** [comment]
Problems solved. I'll proceed to merge now.

**Pull request merged**
