### PR TITLE
hotfix/aleph

### PR DESCRIPTION
**Pull request by mandresm**
- Changed the path of `ECCODESROOT` to one where it was compiled without Skylake optimization, for avoiding the `illegal instruction` error during the use of `grib_set` (preprocessing of AWICM3, in `Aleph`).
- A new log file is included in PBS: `<experiment_id>_execution_<DATE>.log` where the `stdout` and `stderr` are dumped, so that the user can monitor the progress of the simulation, and doesn't need to wait for the `*_compute_*.log` to be written at the end of the simulation. In order to still get the `aprun` `stdout` and `stderr` in the `*_compute_*.log` (for error detection and stopping simulations through ESM-Tools) `tee` command is used for the dumping. The `aprun` command in the `.run` file after these changes looks like this:
```
time aprun -n 40 -N 40 -d 1 env OMP_NUM_THREADS=1 env PMI_LABEL_ERROUT_FORMAT="[FESOM]%l:" ./fesom \
         : -n 80 -N 20 -d 2 env OMP_NUM_THREADS=2 env PMI_LABEL_ERROUT_FORMAT="[OIFS]%l:" ./oifs -v ecmwf -e awi3 \
         : -n 1 -N 1 -d 40 env OMP_NUM_THREADS=40 env PMI_LABEL_ERROUT_FORMAT="[RNFMAP]%l:" ./rnfma  2>&1| tee /scratch/awi/mandresm//tidos_new_grib2/log/tidos_new_grib2_awicm3_execution_20000101-20000101.log &
```
- rcf preprocessing `sed` commands modified. Substitution of variables is now independent on whether all the information goes into one line or several.

### CODE REVIEW

**Comment by mandresm** [comment]
Tested for ALEPH

**Comment by JanStreffing** [comment]
I also very much like the moving logfiles.

**Comment by mandresm** [comment]
> i guess the makeshift solution was easier than finding the root cause of the fortran IO particularity. good job on the `sed` magic

Indeed. I tried it for a while, and my small F90 script was producing the new lines, so I started to suspect it was related to some namelist module, as other files were written correctly and the rcf is a namelist. In any case, it works also with the single line format.

**Review by JanStreffing — APPROVED** [review]

**Comment by mandresm** [comment]
I'm running tests on ollie to verify that I did not break anything in another HPC, after this, I'll merge.

**Comment by mandresm** [comment]
All tests passed in Ollie. I'll be merging to release now:

- awicm3:
    - frontiers:
        - awicm3-frontiers-TCO159L91-CORE2_initial:
            - ollie:    compiles        runs
    - v3.0:
        - awicm3-v3.0-TCO159L91-CORE2_initial:
            - ollie:    compiles        runs
- fesom-recom:
    - 1.4:
        - fesom-recom1.4-initial-daily:
            - ollie:    compiles        runs
- vilma-pism:
    - 1.0v1d:
        - vilma1d_1ky-pism_1y:
            - ollie:    compiles        runs
- awiesm:
    - 2.1-wiso:
        - PI_ctrl_awiesm-2.1-wiso:
            - ollie:    compiles        runs
    - 2.1-recom:
        - all_awiesm-2.1-recom:
            - ollie:    compiles        runs
- awicm:
    - CMIP6:
        - awicm1-CMIP6-initial-monthly:
            - ollie:    compiles        runs
    - 2.0:
        - awicm2-initial-monthly:
            - ollie:    compiles        runs
- fesom:
    - 2.1:
        - fesom2.1-initial-monthly:
            - ollie:    compiles        runs
    - 2.0:
        - fesom2.0-initial-monthly:
            - ollie:    compiles        runs
- echam:
    - 6.3.04p1:
        - echam6.3.04p1-initial-monthly:
            - ollie:    compiles        runs

**Pull request merged**
