### PR TITLE
fix(echam.yaml): updates online handbook with correct licence guidelines

### PR DESCRIPTION
**Pull request by pgierz**
Updates the docs to no longer run into problems for not being able to find the forum link, as described by https://jira-software.awi.de/browse/HELP-26318

### CODE REVIEW

**Review by nwieters — APPROVED** [review]

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
Here a recipe on when and how to use approve changes: https://esm-tools.readthedocs.io/en/latest/esm_tests.html#how-to-approve-changes-on-a-github-pull-request

Only ignore failing albedo tests for now.

**Comment by nwieters** [comment]
There appears no table for Echam (and other components) in the section 'Supported Models' of the documentation. If I create the docs locally (make html) I get the following error:

```
/esm_tools/docs/Supported_Models.rst:22: ERROR: Insufficient data supplied (1 columns(s)); no data remaining for table body, required by "csv-table" directive.

.. csv-table::
   :file: metadata/echam.csv
   :delim: ;
   :widths: 20, 80
   :stub-columns: 1
```

**Comment by pgierz** [comment]
Interesting....readthedocs should have given us an error, and since it didn't, I assumed everything was ok. Have a look where the `Supported_Models.rst` is generated (or rather, where this `metadata/echam.csv` file comes from). That might give us more of a hint...

**Comment by nwieters** [comment]
In docs/conf.py. The yaml files will be translated into *.csv and these are translated into tables for Supported_Models.rst.

**Comment by mandresm** [comment]
#approve-changes, the previous time things failed because the branch was already deleted...

**Pull request merged**
