### PR TITLE
Fesom 2.1

### PR DESCRIPTION
**Pull request by mandresm**
Trying to put together a solid `fesom-2.1.yaml` for `prep_release` and to use in all the current developments that are using `FESOM-2.1` through the `fesom-2.0.yaml`. Contains the changes from #293 plus some additional changes.

Works for:
- Fesom standalone
    - in `ollie`
        - JRA55
        - ERA5

@koldunovn , feel free to comment and test.

### CODE REVIEW

**Comment by koldunovn** [comment]
I did a fresh installation of esm-tools and checkout the branch. 

The generation of the setup seems fine, however we still have problem with stalling run. So using the `fesom2-ollie-initial-monthly.yaml` should run the simulation for one month and resubmit (correct me if I am wrong). What is happening is the simulation is run for one month, output and restarts are created, but then the job just hangs until the time limit is reached, and it stops with:
```
CANCELLED AT 2021-07-30T19:30:01 DUE TO TIME LIMIT
``` 

If you want to look at the setup:
Configuration: `/home/ollie/nkolduno/ESM/esm_tools/runscripts/fesom2/fesom2-ollie-initial-monthly.yaml`
Output: `/work/ollie/nkolduno/fesom2.1_test_miguel/my_second_test/run_20010101-20010131/scripts`

**Review by koldunovn — COMMENTED** [review]
Works for stand alone FESOM2.1 run without `conda`. Would be nice to have a version that play well with conda, but this is a matter of another PR :)

**Review by koldunovn — APPROVED** [review]

**Comment by mandresm** [comment]
Thanks @koldunovn . I'll need to contact @pgierz before merging so that I don't break anything for `awiesm-2`, although this merge goes into `develop`, so it should still be fine.

**Comment by pgierz** [comment]
@koldunovn:
> Works for stand alone FESOM2.1 run without conda. Would be nice to have a version that play well with conda, but this is a matter of another PR :)

Yes...I'd also like to set up some CI to automatically push to PyPI and the equivalent for conda-forge. That would be super. But we need to figure out a way to run automatic tests first, which has been on my list for the last like....year...who knows, someday. We can also at the same time have the magical flying pigs and the goose laying golden eggs. (Remember, a horrible sense of humour is required for any self-respecting programmer)

@mandresm: want me to test drive this branch with one of my standard AWIESM runs? I likely won't get to that until Wednesday unfortunately.

**Comment by pgierz** [comment]
As a separate point: I am super happy we might very soon have FESOM 2.1 support by default. I've been trying to hack stuff in to various users run scripts for the better part of a month. Having this go "out of the box" would be a huge step.

**Comment by mandresm** [comment]
@pgierz , more than anything I'd like to understand to which extent you use the `fesom-2.1.yaml` that is already in `release` and I have some concerns about the `ALE` schemes configurations that seem to be specific to the `awiesm` coupled setup, if I did not understand incorrectly. I can help with the testing if necessary.

**Comment by koldunovn** [comment]
@pgierz Maybe it's not the right place to discuss it, but what is a problem now to do at least initial automatic testing? We can setup some very basic version pretty fast with google actions and FESOM2.1 pi-mesh.

**Comment by pgierz** [comment]
Should be a Separate issue (or Webex chat) but: compiling reliably (ie mirroring the Mistral, Juwels, HLRN, and Ollie software stacks) and echam, just in general.

**Comment by koldunovn** [comment]
@pgierz  I think just testing basic functionality on ubuntu (that FESOM allows), already would catch a lot of simple problems :) I am happy to discuss. This week is relatively free after Tuesday, so maybe let's setup a call, maybe @mandresm is also interested?

**Comment by pgierz** [comment]
Nikolay, after Tuesday? I guess you are teaching tomorrow then. How about Wednesday after the lunch break? 

Miguel, we can still look at the awiesm stuff tomorrow directly. I'm free starting at 14:00

**Comment by koldunovn** [comment]
While trying to do preliminary version of CI for tomorrow, I already catch some error. This is what I get while trying to execute `esm_master`:

```
ERROR: YAML syntax
------------------

The general ``add_namelist_changes`` and ``add_`` in ``choose_`` are not compatible in /esm/esm_tools/configs/setups/awiesm/awiesm-2.1.yaml:
    - choose_general.version.2.1.add_namelist_changes

Note that multiple ``add_<variable>`` in a single file are compatible as long as they are included inside ``choose_`` blocks. An ``add_<variable>`` out of a ``choose_`` block and the same ``add_<variable>`` inside of a ``choose_`` block are considered incompatible. If the general ``add_<variable>`` should be added as a default, please include it to ``<variable>`` instead.
```

**Comment by pgierz** [comment]
See this is exactly why I've been saying auto-testing is an absolute must on a project like this. 

Nikolay I guess we will look more in detail tomorrow, but I think those are changes Miguel and I did this morning, we must have overlook something. Sorry for that. I just finished setting up my own test environment and ran into exactly the same thing, but I won't get to that anymore today. 

Does fesom only work at least?

**Comment by denizural** [comment]
Just to add my 5 cents to Paul: we need to define a set of test runs with selected models from simple to complex. Obviously, this can be an overkill as we support more and more models, maybe running these test on some predefined intervals could be a better choice.

**Comment by koldunovn** [comment]
@pgierz well, I can't run esm_master, so just commented out the lines in question :) Having tests for this kind of things (installing and then running esm_master) can be added immediately. Running models turns out to be a bit more difficult story :)

@denizural The thing that I immediately stumbled upon is the possibility to recognise that we a running on Ubuntu/Docker machine, current mechanism, as far as I can see,  rely on the hostname, and I am not sure how to tell `esm_tools`.

**Comment by denizural** [comment]
@koldunovn, this requires a separate machine yaml file for the hostname of the container. You can run your container (`docker run`) with the option `--hostname` to give a manual hostname but of course GitHub actions is bit different. The official documentation of GitHub actions say:
`The hostname of the service container is automatically mapped to the label name.`

This is what we can do accordingly 

The Fesom workflow lacks the `services` section. You can add this to the job `gfortran_ubuntu`:
```yaml
services:
    redis:  # or nginx, postgres, ...
    image: # docker hub image
```
I never tested these but the `hostname` could be either the `<service_id>` or the value of the `image` key. Maybe we can then also contain a simple machine yaml file for the desired hostname (eg. `test_container.yaml`)

**Comment by koldunovn** [comment]
@denizural I use a brute-force approach in #421  :) For one workflow I setup:

```yaml
container: 
      image: koldunovn/esm_test:latest
      options: --hostname ollie1
```

And for the one that do not use my external container:

```yaml
 - name: run status-fesom-2.0
        run: |
          sudo hostname ollie1
          esm_master status-fesom-2.0
```

**Comment by pgierz** [comment]
I think that one:
> ``` - name: run status-fesom-2.0
>         run: |
>          sudo hostname ollie1
>           esm_master status-fesom-2.0
> ```
might just be a nice candidate for the newest in the list of "Paul's favorite computing moment of the week". But I also had user recently do this:
```
alias python="module load python"
```

**Comment by koldunovn** [comment]
> I think that one:
> 
> > ```
> >         run: |
> >          sudo hostname ollie1
> >           esm_master status-fesom-2.0
> > ```
> 
> might just be a nice candidate for the newest in the list of "Paul's favorite computing moment of the week". But I also had user recently do this:
> 
> ```
> alias python="module load python"
> ```

Turns out you should do it only once per `steps` :) There maybe some more elegant way to execute it before all the steps though :)

**Comment by pgierz** [comment]
Thanks for the fix @mandresm. I guess this solves the parser problem Nikolay was having? 

I'll set up my test and let you know sometime around lunch.

**Comment by mandresm** [comment]
> While trying to do preliminary version of CI for tomorrow, I already catch some error. This is what I get while trying to execute `esm_master`:
> 
> ```
> ERROR: YAML syntax
> ------------------
> 
> The general ``add_namelist_changes`` and ``add_`` in ``choose_`` are not compatible in /esm/esm_tools/configs/setups/awiesm/awiesm-2.1.yaml:
>     - choose_general.version.2.1.add_namelist_changes
> 
> Note that multiple ``add_<variable>`` in a single file are compatible as long as they are included inside ``choose_`` blocks. An ``add_<variable>`` out of a ``choose_`` block and the same ``add_<variable>`` inside of a ``choose_`` block are considered incompatible. If the general ``add_<variable>`` should be added as a default, please include it to ``<variable>`` instead.
> ```

I've fixed this issue. This error makes sure things are written in a way that no conflicts arise from the use of `namelist_changes` using them from a `choose_` or with and `add_`. For now quite some time `namelist_changes` are complementary combined with `namelist_changes` from other files. That means you can have one `namelist_changes` per model section in your yamls (or if you keep them under the same choose, more than one) and that the `add_namelist_changes` are better used inside `choose_blocks`. 

There is still another bug that I found when testing the `choose_blocks` and the `namelist_changes` in `awiesm-2.1.yaml`: the `choose_` in won't work correctly if the cases instead of being `"2.1"` are `2.1`. I'll have to look at this in more detail, but I'll talk to @denizural first, I think he has been already working on this.

**Comment by mandresm** [comment]
@pgierz my last commit solved the problem of the `choose_` by making the cases be strings. I tested the two different `ALE_scheme` options from the runscript with check runs and looked at the resulting `config/*_finished_*.yaml`. The final `namelist_changes` look right in both cases but a real test is still needed.

I also needed to add a `remove_` to ignore the `namelist_changes` for the fesom forcing. Those have dependencies to other variables that are defined for the forcing case and obviously it's complaining about these variables not existing.

**Comment by mandresm** [comment]
@koldunovn , the changes in c1217ef for `mistral`'s forcing and climate paths should be okay right? At least it runs and restarts.

**Comment by mandresm** [comment]
FESOM-2.1 compiles and runs in:
- Ollie
- Mistral
- HLNR (JRA55 pool to be fixed, missing two files)
- JUWELS (I used AWICM3 @JanStreffing input and meshes for CORE2 forcing, all defined in the runscript, so no default pools given, but I guess this is fine, as JUWELS does not really support real pools)

From my side this is ready to merge into `develop`, `prep_release`, and the other branches that are using currently `fesom-2.1` through the `fesom-2.0.yaml`.

**Comment by koldunovn** [comment]
> @koldunovn , the changes in [c1217ef](https://github.com/esm-tools/esm_tools/commit/c1217ef25545b356a91d84f8bbee709ebc3cfb5f) for `mistral`'s forcing and climate paths should be okay right? At least it runs and restarts.

That's right, thanks for fixing it! I never get passed the ollie for the testing :)

**Comment by koldunovn** [comment]
> FESOM-2.1 compiles and runs in:
> 
> * Ollie
> * Mistral
> * HLNR (JRA55 pool to be fixed, missing two files)
> * JUWELS (I used AWICM3 @JanStreffing input and meshes for CORE2 forcing, all defined in the runscript, so no default pools given, but I guess this is fine, as JUWELS does not really support real pools)
> 
> From my side this is ready to merge into `develop`, `prep_release`, and the other branches that are using currently `fesom-2.1` through the `fesom-2.0.yaml`.

BTW, I have updated `JRA55-do-v1.4.0` with data from 2019 and 2020 for `ollie` and (just few minutes ago) for `mistral`,  so if you have some other places with this forcing dataset, you can use them as a source now :) Would be great to have a system in place that do this automatically, but, well... :)

**Comment by mandresm** [comment]
> > FESOM-2.1 compiles and runs in:
> > 
> > * Ollie
> > * Mistral
> > * HLNR (JRA55 pool to be fixed, missing two files)
> > * JUWELS (I used AWICM3 @JanStreffing input and meshes for CORE2 forcing, all defined in the runscript, so no default pools given, but I guess this is fine, as JUWELS does not really support real pools)
> > 
> > From my side this is ready to merge into `develop`, `prep_release`, and the other branches that are using currently `fesom-2.1` through the `fesom-2.0.yaml`.
> 
> BTW, I have updated `JRA55-do-v1.4.0` with data from 2019 and 2020 for `ollie` and (just few minutes ago) for `mistral`, so if you have some other places with this forcing dataset, you can use them as a source now :) Would be great to have a system in place that do this automatically, but, well... :)

yeah, one day...

**Pull request merged**
