### PR TITLE
Feature/add foci postprocessing example cleanup

### LINKED ISSUE #554: multiple postprocessing scripts screw script generation
**Describe the bug**
If I add a postprocessing section for two components (echam and nemo in foci.yaml) of a coupled setup (see 
https://github.com/esm-tools/esm_tools/blob/ab2e86ead81a83e6f043ff8d403056378cf8c9d1/configs/setups/foci/foci.yaml#L281-L299
and
https://github.com/esm-tools/esm_tools/blob/ab2e86ead81a83e6f043ff8d403056378cf8c9d1/configs/setups/foci/foci.yaml#L385-L403
then, one postprocessing script is generated that contains the call to both postprocessing scripts:
```bash
#!/bin/bash
#SBATCH --partition=standard96
#SBATCH --time=06:00:00
#SBATCH --ntasks=2
#SBATCH --output=/home/shkifmsw/esm/esm-experiments//viking10_initial_pp2/log/viking10_initial_pp2_foci_postprocessing_18510101-18511231.log --error=/home/shkifmsw/esm/esm-experiments//viking10_initial_pp2/log/viking10_initial_pp2_foci_postprocessing_18510101-18511231.log
#SBATCH --job-name=viking10_initial_pp2
#SBATCH --account=shk00018
#SBATCH --mail-type=NONE
#SBATCH --ntasks-per-core=1
#SBATCH --exclusive

module purge
module load slurm
module load HLRNenv
module load sw.skl
module load cmake
module load cdo nco
module load intel/19.0.5
module load impi/2019.5
source $I_MPI_ROOT/intel64/bin/mpivars.sh release_mt

export LC_ALL=en_US.UTF-8
export FC=mpiifort
export F77=mpiifort
export MPIFC=mpiifort
export FCFLAGS=-free
export CC=mpiicc
export CXX=mpiicpc
export MPIROOT="$(mpiifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export IO_LIB_ROOT=/home/shkifmsw/sw/HPC_libraries/intel2019.0.5_impi2019.5_20200811
export PATH=$IO_LIB_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$IO_LIB_ROOT/lib:$LD_LIBRARY_PATH
export SZIPROOT=$IO_LIB_ROOT
export HDF5ROOT=$IO_LIB_ROOT
export HDF5_ROOT=$HDF5ROOT
export NETCDFROOT=$IO_LIB_ROOT
export NETCDFFROOT=$IO_LIB_ROOT
export ECCODESROOT=$IO_LIB_ROOT
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export HOME=/home/shkifmsw
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo $(date +"%a %b  %e %T %Y") : postprocessing_echam 2 1851-01-01T00:00:00 3403556 - start >> /home/shkifmsw/esm/esm-experiments//viking10_initial_pp2/log//viking10_initial_pp2_foci.log

cd /home/shkifmsw/esm/esm-experiments//viking10_initial_pp2/run_18510101-18511231/work/
time srun --mpi=pmi2 -l --kill-on-bad-exit=1 --cpu_bind=cores --distribution=cyclic:cyclic --export=ALL /home/shkifmsw/esm/esm_tools/configs/.//setups/foci/echam_postprocessing.sh -r viking10_initial_pp2 -s 1851 -e 1851 2>&1 &
module purge
module load slurm
module load HLRNenv
module load sw.skl
module load cmake
module load cdo nco
module load intel/19.0.5
module load impi/2019.5
source $I_MPI_ROOT/intel64/bin/mpivars.sh release_mt

export LC_ALL=en_US.UTF-8
export FC=mpiifort
export F77=mpiifort
export MPIFC=mpiifort
export FCFLAGS=-free
export CC=mpiicc
export CXX=mpiicpc
export MPIROOT="$(mpiifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export IO_LIB_ROOT=/home/shkifmsw/sw/HPC_libraries/intel2019.0.5_impi2019.5_20200811
export PATH=$IO_LIB_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$IO_LIB_ROOT/lib:$LD_LIBRARY_PATH
export SZIPROOT=$IO_LIB_ROOT
export HDF5ROOT=$IO_LIB_ROOT
export HDF5_ROOT=$HDF5ROOT
export NETCDFROOT=$IO_LIB_ROOT
export NETCDFFROOT=$IO_LIB_ROOT
export ECCODESROOT=$IO_LIB_ROOT
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export HOME=/home/shkifmsw
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo $(date +"%a %b  %e %T %Y") : postprocessing_nemo 2 1851-01-01T00:00:00 3403556 - start >> /home/shkifmsw/esm/esm-experiments//viking10_initial_pp2/log//viking10_initial_pp2_foci.log

cd /home/shkifmsw/esm/esm-experiments//viking10_initial_pp2/run_18510101-18511231/work/
time srun --mpi=pmi2 -l --kill-on-bad-exit=1 --cpu_bind=cores --distribution=cyclic:cyclic --export=ALL /home/shkifmsw/esm/esm_tools/configs/.//setups/foci/nemo_postprocessing.sh -m -r viking10_initial_pp2 -s 1851 -e 1851 2>&1 &

wait
```
This script is called TWICE add exactly the same time by the workflow manager.
**To Reproduce**
see above

**Expected behavior**
Two scripts that are executed independent of each other as separate jobs. I went through the code a bit and there a things such as `subjob_clusters` etc. but I couldn't find any documentation on how to use those settings.

**Screenshots**

**System (please complete the following information):**
 - Supercomputer: glogin
 - Version: latest release

### PR DESCRIPTION
**Pull request by seb-wahl**
added automatic postprocessing for FOCI
cleanup in runscripts/foci/
closes #554

### CODE REVIEW

**Review by mandresm — APPROVED** [review]
Thanks @seb-wahl all looks good from my side. Following what we've being saying lately, this being a feature, should mean a new minor version instead of a patch. @denizural , @pgierz , what do you think? should we label this as 6.1.0 or as 6.0.10?

**Comment by pgierz** [comment]
I would go with `6.1.0`, as it is a new feature, albeit a small one. Strictly speaking, changing the minor number implies that all bugs are out of `6.0.x`, but we can just keep fixing things as we go.

**Comment by mandresm** [comment]
@pgierz , I agree with that. @seb-wahl , I've seen you made some recent changes, please, let me know when this can be merged, and I'll take care of bumping the version and putting it into release.

**Comment by seb-wahl** [comment]
> @pgierz , I agree with that. @seb-wahl , I've seen you made some recent changes, please, let me know when this can be merged, and I'll take care of bumping the version and putting it into release.

I just removed a `set -x` in one of the postprocessing scripts, so go ahead and merge

**Comment by pgierz** [comment]
Not small, that was the wrong word: restricted to geomar models ;-) still, I would say a new minor number is warranted. Then @seb-wahl has a very obvious road marker to tell his users "if you aren't above 6.1.x, something might not work". I will then do the same thing once awiesm converges...sometime soon I hope.

**Pull request merged**
