### PR TITLE
adjusting the AWIESM recipes to the new recipe logic

### PR DESCRIPTION
**Pull request by mandresm**
Adjusts the AWIESM recipes to the new recipe logic.

It still needs to be tested. But it should work... (something similar works for `OpenIFS`).

### CODE REVIEW

**Review by pgierz — COMMENTED** [review]
Alright, the changes themselves look good. I have one question, and then a few things I need to check:

Question: Where is the `venv_bootstrap` step?

For me to look into:
It says "all checks passed", but if you looks a bit more carefully at the checks tab, it seems as if some tests did not even get triggered, see here that the circle is only halfway green:
https://github.com/esm-tools/esm_tools/pull/534/checks

**Comment by mandresm** [comment]
I don't understand the outcome of those checks... I still need to get familiar with those.

The tests I run on ollie for AWIESM worked well and they also include the `hosing_files` operations (at least ESM-Tools is reporting that that step is run).

As now each simulation consists of several tasks, each task has it's own recipe. I think the old recipe in AWIESM was simply trying to add the `add_hosing_files` step, that would go into the recipe of the `prepcompute` task. `venv_bootstrap` is part of `prepexp` recipe:
https://github.com/esm-tools/esm_tools/blob/bc3cb779c34c50d244a7742f5561e7ac76421b67/configs/esm_software/esm_runscripts/esm_runscripts.yaml#L40-L47

**Comment by pgierz** [comment]
Ah, alright, and since we only override specific recipes from the setup to the task flow, if we don't define one (such as `prepexp`) it just takes the default? 

For the missing checks, I can give an overview in our first monday meeting after the holidays

**Comment by mandresm** [comment]
> Ah, alright, and since we only override specific recipes from the setup to the task flow, if we don't define one (such as `prepexp`) it just takes the default?

Correct!

**Comment by pgierz** [comment]
OK, I found out why those other checks were not triggered. It seems that you need to specify a version. I put a notes and reference to the GitHub docs in my commit 88dae62a2f4a1e.

This may result in some of the same failures as documented in #533

**Review by pgierz — APPROVED** [review]
@mandresm go ahead and merge this with version bump and all that. The failing CI tests are the same as the one I reported in the issue, so, that isn't related to this PR.

How did we normally do this? Bump the version and add the tag in the PR branch, or merge, and then do that in the release branch?

**Comment by mandresm** [comment]
> @mandresm go ahead and merge this with version bump and all that. The failing CI tests are the same as the one I reported in the issue, so, that isn't related to this PR.
> 
> How did we normally do this? Bump the version and add the tag in the PR branch, or merge, and then do that in the release branch?

The way I do it is the way you taught me some time ago :) : first bumpversion, and then merge into release and develop.

**Pull request merged**
