### PR TITLE
changes in the default variant, now gamma

### PR DESCRIPTION
**Pull request by mandresm**
@fernandadialzira pointed out yesterday that the default `general.variant: beta` in `aiwesm-2.1.yaml` is incorrect and it should be `gamma`. I changed that. However, when looking at the `fesom` section of the `awiesm-2.1.yaml` we can notice the following:

https://github.com/esm-tools/esm_tools/blob/17ad18361418606fac4e394f2d6a2fa08abe2130/configs/setups/awiesm/awiesm-2.1.yaml#L298-L300

This lines control whether `K_gm_max` is removed from the namelist (for `beta`) or not (any other variant). The problem I see is that `K_gm_max` is also controlled here:

https://github.com/esm-tools/esm_tools/blob/17ad18361418606fac4e394f2d6a2fa08abe2130/configs/setups/awiesm/awiesm-2.1.yaml#L271-L296

**There is therefore a** `choose_` **conflict here, where there is no way of knowing what value** `fesom.K_gm_max` **will take.**

The current options (a written summary of the current conflicts) are as follow:

1. If AWI-ESM is any variant of version `2.1`, for the `ALE_schemes` `zstar` and `linfs` the `K_gm_max` in the namelist is switch to `2000.0`
2. If `default.variant` is `beta` removes `K_gm_max` from the namelist.

My question for @pgierz and @fernandadialzira: is it possible that someone wants to run `zstar` or `linfs` with a `2.1` version in the `beta` variant (removing `K_gm_max`)? If that's the case I would suggest the following:
1. Remove `K_gm_max` from the `choose_version_2_1.True` since there it is always by default `2000.0`
2. Add a the following `gamma` option:
```
        choose_general.variant:
            beta:
                K_gm_max: "remove_from_namelist"
            gamma:
                K_gm_max: 2000.0
```

### CODE REVIEW

**Comment by fernandadialzira** [comment]
If I am not mistaken, the beta and the gamma variant are from two different fesom versions, not only the `ALE scheme`. So if one would work with the `beta` variant, he/she would be working with `fesom2.0` and the `linfs` `ALE scheme`. On the other hand, for the `gamma` variant, the fesom version is 2.1 and the `ALE scheme` is `zstar`. 

In my opinion, we would not need to include this variable variant, either gamma or beta, neither the choose block for it, as in the choose block for the model the ALE scheme is defined. Perhaps all would be solved if this part would be:  

`variant: beta` - delete

>                          version_2_1: "$(( '2.1' in '${general.version}' ))"
>                                  choose_version_2_1:
>                                          True:
>                                                  # NOTE: move potentially to AWIESM 2
>                                                  ## Settings for Gent/McWilliams based upon the selected ALE scheme.
>                                                  K_gm: 3000.0
>                                                  K_hor: 3000.0
>                                                  K_gm_max: 2000.0
>                          
>                                                  choose_ALE_scheme:
>                                                      linfs:
>                                                          K_gm: 5000.0
>                                                          K_hor: 5000.0
>                                                          K_gm_max: remove_from_namelist
>                                                      zstar:
>                                                          K_gm_max: 2000.0
>                                                          K_hor: 3000.0
>                                                          K_gm: remove_from_namelist
>                                                      "*":
>                                                          is: invalid
>                          
>                                                  add_namelist_changes:
>                                                      namelist.oce:
>                                                          oce_dyn:
>                                                              K_gm: ${K_gm}
>                                                              K_gm_max: ${K_gm_max}
>                                                          oce_tra:
>                                                              K_hor: ${K_hor}

   And delete the following.

>                             choose_general.variant:
>                                      beta:
>                                          K_gm_max: "remove_from_namelist"

However, as the zstar only has K_hor and K_gm_max, and both are the default values already detailed in `fesom2.1`'s `namelist.oce`, could it also work?:

`variant: beta` - delete

>                         version_2_1: "$(( '2.1' in '${general.version}' ))"
>                                  choose_version_2_1:
>                                          True:
>                                                  choose_ALE_scheme:
>                                                      linfs:
>                                                          K_gm: 5000.0
>                                                          K_hor: 5000.0
>                                                      "*":
>                                                          is: invalid
> 
>                                                  add_namelist_changes:
>                                                      namelist.oce:
>                                                          oce_dyn:
>                                                              K_gm: ${K_gm}
>                                                          oce_tra:
>                                                              K_hor: ${K_hor}

   And delete the following:

>                             choose_general.variant:
>                                      beta:
>                                          K_gm_max: "remove_from_namelist"

So that only the values would change if we would be specifying the `linfs` `ALE scheme`?

**Comment by mandresm** [comment]
I agree that if `gamma` and `beta` are specific to the fesom version, and all of our fesom versions in `awiesm-2.1.yaml` are `2.1` then there is no point of having such an option: it's all `gamma` and we can delete the `variant` and the `choose_general.variant` block.

About the second part of the email:

> However, as the zstar only has K_hor and K_gm_max, and both are the default values already detailed in `fesom2.1`'s `namelist.oce`, could it also work?:

Are you suggesting to remove the `zstar` case because these options are the ones provided with the default `fesom` namelist? If that's the case, I will still leave it there. The reason for that is that imagine someone is using their own namelists and those variables deviate from the default, and then they try to set `ALE_scheme: zstart`. Instead of getting `zstar` they will get whatever they put in their namelist and that will be confusing. Would you agree @fernandadialzira ?

**Comment by fernandadialzira** [comment]
I completely agree! Thank you for the clarification. I also set the `ALE scheme` in previous simulations, and I understand it can create trouble if it is not well defined. So perhaps we edit this part of `awiesm-2.1.yaml` to my first suggestion if you and @pgierz agree. In this way we delete the blocks to choose the variant and only add a `k_gm_max: remove_from_namelist` on the `linfs` `ALE scheme` section.

**Comment by pgierz** [comment]
Apologies for the late response:

> is it possible that someone wants to run zstar or linfs with a 2.1 version in the beta variant (removing K_gm_max)?

Short answer: no. `zstar` should actually only be possible via `gamma` without serious under the hood changes. That requires namelist changes, model changes, and more than I would be comfortable giving a default user to work on...

Shorter answer: I need to give a talk about version numbers to paleodyn and how to write version numbers down. Let's say this is my next windmill to charge against....

**Comment by mandresm** [comment]
Okay, so I will then proceed to do what was agreed with @fernandadialzira : remove the variant option.

**Comment by mandresm** [comment]
Testing now. @pgierz , if you agree with it would you approve the PR? I will merge after successful tests.

**Comment by pgierz** [comment]
Which PR is that?

**Comment by mandresm** [comment]
This one :)

**Comment by pgierz** [comment]
And as to failing checks....I am on that. There is a fix after a long combat with the GitHub Actions, but I want to cover all cases listed in #533 fixed before that goes in all the way

**Comment by pgierz** [comment]
@mandresm sorry, I thought I was in an issue thread. too many thing are happening at once...

**Review by pgierz — APPROVED** [review]
👍🏻

Before this actually goes in and creates a new version number, we are sure it works, right? (@fernandadialzira your run functions with this version?) The config changes seem harmless enough, but in honesty I have not run a real production model in a while thus I am only doing "visual checks"....

**Comment by mandresm** [comment]
I am running `awiesm-2.1-wiso` and `awiesm-2.1-recom` monthly restarts, 2 months (the runscripts I have implemented in esm_tests). I'll also wait for @fernandadialzira for her own tests.

**Comment by fernandadialzira** [comment]
I am currently stuck on [this problem](https://github.com/esm-tools/esm_tools/issues/154#issuecomment-1048969256) referenced here in #154. So when I try to run any test I am getting the same error regarding the echam libraries. If you @mandresm and @pgierz have any ideas I could try. As in my explanation there, I tried several ways to handle the library problem, but so far no resolution.

**Comment by mandresm** [comment]
Currently running esm_tests in ollie

**Comment by fernandadialzira** [comment]
@mandresm and @pgierz

After Paul found out that to run the bootstrap simulations we needed to switch to echam `ice` branch, I ran this with the esm-tools `release` and `fix/awiesm_default_variant` branches and both simulations worked out. 
In fact, by using this branch I am also able to run rho-amoc simulations which require wiso turned off. With release, it would still find the isotopes fields, and I would have to comment them out by hand in `echam.yaml`. 

So from my tests, this could be merged to the main branch

**Comment by pgierz** [comment]
I think this PR will be superseded by #623?

**Comment by pgierz** [comment]
I think this PR will be superseded by #623?

**Comment by fernandadialzira** [comment]
Yes, at least from what I have seen of #623, the changes in this will be applied there, but meanwhile I am still using this branch

**Comment by mandresm** [comment]
> I think this PR will be superseded by #623?

I'll be closing it then. I'll keep the branch alive for @fernandadialzira

**Pull request closed without merging**
