### PR TITLE
Feature/add oifs 43r3 v1

### PR DESCRIPTION
**Pull request by joakimkjellsson**
I have added a new OpenIFS version, 43r3-v1 based on 43r3v1 from ECMWF. 
This version can run with XIOS. 
40r1 and the standard 43r3 may be removed in the future, but let's keep them for now. 

I have made sure this version of OpenIFS can run standalone. Restart work. XIOS output works. 
The output is not moved to outdata directory as it should, but that's a later problem.

### CODE REVIEW

**Comment by pgierz** [comment]
I just rebased this to start from develop. If @seb-wahl understands everything and approves, we will put it in.

**Review by seb-wahl — APPROVED** [review]
Tested it and it works, added storing of NetCDF output from xios in my commit (@joakimkjellsson).

**Comment by seb-wahl** [comment]
> Tested it and it works, added storing of NetCDF output from xios in my commit (@joakimkjellsson).

Paul, could you wait with merging until we did some fine-tuning on this. Will most likely be done by tomorrow lunch-time.

**Comment by pgierz** [comment]
Ok just give me a sign

**Comment by joakimkjellsson** [comment]
Yes please wait a bit. I realised, stupidly, that my commits only included my recent changes in the runsripts and not the oifs.yaml. 
I have done git pull and merged with remote (@seb-wahl new fixes). Will do another push soon when I know it works.

**Comment by joakimkjellsson** [comment]
Done! I have tested this and I can successfully run 1 year with monthly restarts. restarting works and outdata is moved properly after a run. 
@seb-wahl or @pgierz feel free to merge if all is fine on your end.

**Comment by pgierz** [comment]
Since this is a feature, it will be going into develop rather than release (and be included in the next release, either 4.3, or 5.0 depending on what number we pick. That'll be in October sometime I guess). Is that OK for you guys?

**Comment by joakimkjellsson** [comment]
Makes sense to me :-) 👍

**Comment by pgierz** [comment]
OK. We have our big Helmholtz Internal Program funding shindig today, so if I don't get to it by 9, I'll do it over lunch or Sebastian can take care of it :-)

**Comment by pgierz** [comment]
Hey @joakimkjellsson: this seemed to branch off from something earlier than `4.2.0`, can you rebase it to start there? Reason behind this is that I'd like to keep the branches a bit "cleaner" for the next release, which is planned for October, and new features should start from the latest release. That will considerably reduce the chance of us accidentally merging in old code and "re-break" something that used to work.

**Comment by joakimkjellsson** [comment]
Hi all
Is this pull request done? Should we close off this branch and I'll go back to using "develop"? 

Cheers
Joakim

**Pull request merged**
