### PR TITLE
Feat/esm tests

### PR DESCRIPTION
**Pull request by mandresm**
esm_tests still needs quite a bit of work, but I am using it very regularly. Although I have no time to work on making it more general or implementing in the CI now, I would like to merge this, because it puts all the testing information in another repository using git submodules, meaning I could keep updating the esm_test information (very much needed for checking changes from fix to fix) without messing the PRs of ESM-Tools.

I think of this more of a fix than a feature. When I finish with esm_tests completely then it will be a feature.

### CODE REVIEW

**Comment by pgierz** [comment]
Fine with me!

**Review by pgierz — APPROVED** [review]

**Comment by denizural** [comment]
I see that there are some conflicts

**Comment by mandresm** [comment]
Yes, they have to be solved manually, I'm working on them. Is basically removing all the information files.

**Comment by mandresm** [comment]
#bump

**Comment by mandresm** [comment]
#bump #patch

**Comment by mandresm** [comment]
Now it should work (there was a problem where this branch is called `feat` but I actually want to override that with my:
#bump #patch
Hopefully, that worked out

**Comment by pgierz** [comment]
At some point (not today anymore) I want to find a way to trick GitHub Actions to use the labels of the PR instead of comments in the thread. Or just do it all automatically. But, my polite question to the community remains ignored :-(

https://github.community/t/automation-for-merging/229797

**Pull request merged**
