### PR TITLE
Draft: Feat/awicm3 v3.3

### PR DESCRIPTION
**Pull request by JanStreffing**
WIP

### CODE REVIEW

**Comment by JanStreffing** [comment]
Currently failing with:

```
 python -mpdb ~/.local/bin/esm_master recomp-awicm3-v3.3/rnfmap
> /home/a/a270092/.local/bin/esm_master(3)<module>()
-> import re
(Pdb) c
Traceback (most recent call last):
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/a/a270092/.local/bin/esm_master", line 3, in <module>
    import re
  File "/home/a/a270092/esm_tools/src/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/home/a/a270092/esm_tools/src/esm_master/esm_master.py", line 55, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepare.py", line 17, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270092/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/batch_system.py", line 685, in find_openmp
    config2 = prepare.resolve_some_choose_blocks(config2)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepare.py", line 124, in resolve_some_choose_blocks
    model_env_into_computer(config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepare.py", line 193, in model_env_into_computer
    esm_parser.basic_choose_blocks(modelconfig["environment_changes"], config)
  File "/home/a/a270092/esm_tools/src/esm_parser/esm_parser.py", line 1244, in basic_choose_blocks
    basic_add_entries_to_chapter_in_config(config_to_resolve)
  File "/home/a/a270092/esm_tools/src/esm_parser/esm_parser.py", line 1101, in basic_add_entries_to_chapter_in_config
    add_entries_from_chapter(config, add_chapter.replace("add_", ""), add_entries)
  File "/home/a/a270092/esm_tools/src/esm_parser/esm_parser.py", line 854, in add_entries_from_chapter
    dict_merge(
  File "/home/a/a270092/esm_tools/src/esm_parser/esm_parser.py", line 639, in dict_merge
    for k, v in merge_dct.items():
AttributeError: 'list' object has no attribute 'items'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/a/a270092/esm_tools/src/esm_parser/esm_parser.py(639)dict_merge()
-> for k, v in merge_dct.items():
(Pdb) exit
Post mortem debugger finished. The /home/a/a270092/.local/bin/esm_master will be restarted
> /home/a/a270092/.local/bin/esm_master(3)<module>()
-> import re
(Pdb) exit
```

Not quite sure what this is. For info: I'm trying to disentangle the rnfmap compile flags from the OIFS_* variables in oifs.env.yaml. the OIFS compile flags are currently not set in the new oifs48.env.yaml. But more than that, I think it's not good practise.

**Comment by mandresm** [comment]
HI Jan, I just fixed the problems with the rnfmap environments. Is not possible to mix list environments and dict environments within the same component, unless they are in different choose and both can never be rich. This problem will vanish when we deprecate the list environments, and one can only use dict environments, which will happen soon...

**Comment by mandresm** [comment]
That being said, the `add_further_reading` of the version choose in awicm3.yaml are not working. Were they working before?

**Comment by JanStreffing** [comment]
This MR still has all the old standalone commits for oifs-48r1. I will close and open a new one.

**Pull request closed without merging**
