### PR TITLE
Oifs48r1 further reading

### LINKED ISSUE #1085: further_reading with esm_master
For the new oifs48r1 I want a separate oifs.env.yaml, which I called oifs48.env.yaml
At first I tried to place the different further reading blocks into the compile_infos like so:
```
compile_infos:
        choose_version:
          48r1:
            branch: main
            comp_command: "./openifs-bundle build --threads=32 --arch=esm_tools --openifs-only --without-double-precision --install; chmod -R ${source_code_permissions} .; mv install/bin/ifsMASTER.SP install/bin/oifs"
            clean_command: ./openifs-bundle build --clean
            git-repository: https://gitlab.dkrz.de/ec-earth/oifs-48r1.git
            install_bins: install/bin/oifs
            destination: oifs-48r1
            further_reading:
              - oifs/oifs48.env.yaml
```
Since this did not seem to do anything I instead placed it in the version choose block:
```
choose_version:
        48r1:
                further_reading:
                        - oifs/oifs48.env.yaml
```
Again no luck.
I'm trying to get these variables into the compile script:

```
# Setup up compile and runtime environment i.e. what needs
# to be changed w.r.t the default config/machines/<computer>.yaml
compiletime_environment_changes:
  choose_computer.name:
    juwels:
      add_export_vars:
        - OIFS_CYCLE: 48r1
        - OIFS_HOME: "${model_dir}"
        - OIFS_LOGFILE: "$OIFS_HOME/oifs_test_log.txt"
        - OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"

environment_changes:
  OpenMP_flag: ""
  OpenMP_CCDEFS: ""
```

You can find my attempts at:
https://github.com/esm-tools/esm_tools/tree/oifs48r1

### PR DESCRIPTION
**Pull request by nwieters**
This PR solves the option to put a further_reading entry inside a choose_version block.

closes #1085

### CODE REVIEW

**Comment by nwieters** [comment]
Hi @JanStreffing , @mandresm ,

this PR now enables to set `further_reading` inside a `choose_version` block.
I still need to test this, if it also works for setups.

I am not sure if this is the most elegant way. I had to workaround the fact that the function `resolve_choose_with_var` only searches for the variable `version` in a component config section and not in the general part. This is probably only needed for standalone models. And if the `version` variable is defined in the runscript general section. I hope I understood this correctly.

In the oifs48.env.yaml I had to comment out the settings for juwels since it complained about conflicting settings in a machine file.

**Comment by nwieters** [comment]
For setups it doesn't work so far.
For example: awicm3
It is complaining that in further_reading file oifs.env.yaml many of the ${computer.<somevar>} variables can not be resolved. 
Strangely also variables that are called for choose_computer block for mistral are tried to be resolved.

**Comment by mandresm** [comment]
The problems that @nwieters is facing are related to versions not being copied early enough from `general` to `oifs` section. I have modified that function and put it earlier in the workflow to solve the problem in #1097

**Comment by nwieters** [comment]
Ok. Thank you @mandresm . I guess this PR is obsolete now. I will close it.

**Pull request closed without merging**
