### PR TITLE
fix/recursive resolution of early variables and fix find_key

### PR DESCRIPTION
**Pull request by mandresm**
This PR fixes the following problem affecting the version switching of FESOM in the PR by @JanStreffing #1056:

In *awicm3.yaml*:

```yaml
fesom:
    version: "2.0"
    choose_general.major_version:
        "3.2":
            version: "2.5"
```

When `general.major_version: "3.2"` the `version` was still `"2.0"` because of several bugs in `esm_parser`.

@seb-wahl  I think you have encounter this problem on the past.

To solve the bugs the following changes have been carried out:

- add recursion to resolve_choose_with_var so that variables that depend on other choose_ blocks can be resolved in early stages if needed.
- fix an issue with find_key to always continue searching into dictionaries to avoid returning only the first match within a path.
- add the early resolution of choose blocks containing component versions in early stages so that the correct yaml file of the component can be loaded.
- improve and clean the code for filtering of found paths to search for chooses containing the desired variable.

### CODE REVIEW

**Comment by JanStreffing** [comment]
Thank you very much @mandresm. I'll get around to testing this in 2 weeks. If someone else wants to give it ago before then, by all means: go :)

**Comment by nwieters** [comment]
I can't really do a full test. When I try to create this situation by adding a fesom version 2.5 into awicm3 v3.1 choose block (in awicm3.yaml), I get an error because of missing coupling fields.
But I debugged it, and I see the fesom version 2.5 in the config dict. I also think that I would not get this error message if the 'correct' version had not been taken. (in this case 2.5).

**Review by nwieters — APPROVED** [review]

**Comment by mandresm** [comment]
Differences with the older tests are minimal and should not create any problem, therefore, #approve-changes

**Comment by mandresm** [comment]
#bump

**Comment by mandresm** [comment]
#bump

**Comment by mandresm** [comment]
#bump

**Pull request merged**
