### PR TITLE
cleanup: move workflow manager examples to seperate folder

### PR DESCRIPTION
**Pull request by pgierz**

### CODE REVIEW

**Review by denizural — APPROVED** [review]
👍

**Comment by pgierz** [comment]
Opps...

#bump

**Comment by pgierz** [comment]
#bump

@mandresm sorry to summon you on your non-support day, but I may have messed something up :-(

**Comment by denizural** [comment]
@pgierz, what is wrong?
PS: Ok, now I see what went wrong. You bumped twice

**Comment by mandresm** [comment]
Why do you think you messed up something? I think it's all fine.

**Comment by pgierz** [comment]
I bumped the version number once too often (no problem really), and not suddenly both release and develop do not have the renamed and moved files.

**Comment by pgierz** [comment]
Alright no one touch anything please. I need to force push once it seems.

@denizural there is the second PR I opened today with fixes for CI. Please also wait there until I fix my own mess.

sorry...

**Pull request merged**
