### PR TITLE
fix(awiesm.yaml): enable dynveg by default for AWIESM 2.1 runs

### PR DESCRIPTION
**Pull request by pgierz**
AWI-ESM should have dynamic vegetation enabled by default. This is controlled via the switch:

```
jsbach:
   dynamic_vegetations: True
```

That is now hard-coded as a default, and can be turned *off* again via the runscript if wanted.

### CODE REVIEW

**Review by denizural — APPROVED** [review]

**Comment by pgierz** [comment]
#bump

**Comment by mandresm** [comment]
#approve-changes

**Comment by pgierz** [comment]
@mandresm can I do both at once? e.g. `$bump $approve-changes`?

**Comment by mandresm** [comment]
I think that should be possible, but $approve-changes is not working -.-

**Comment by mandresm** [comment]
let's try it now! #approve-changes!

**Comment by mandresm** [comment]
#approve-changes...

**Comment by mandresm** [comment]
#approve-changes...

**Comment by mandresm** [comment]
#approve-changes!

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Pull request merged**
