### PR TITLE
fixes default iodefs so that we use 2 layer servers

### PR DESCRIPTION
**Pull request by JanStreffing**
Some of the seldom used default iodef xml files were configured wrongly, resulting in OIFS-XIOS output files that are split by region instead of by variable. This fixes the problem.

### CODE REVIEW

**Review by joakimkjellsson — APPROVED** [review]

**Comment by JanStreffing** [comment]
ty @joakimkjellsson 
@nwieters okay for merge from my side. Failing check is about divergent pool dir on albedo. Perhaps of interest for @mandresm. We can talk about it after I'm back. Unrelated to the merge at hand.

**Comment by nwieters** [comment]
#bump

**Comment by nwieters** [comment]
Hi @JanStreffing, can the branch be deleted?

**Comment by JanStreffing** [comment]
yes

**Pull request merged**
