### PR TITLE
changing nproca times nprocb into nproc

### PR DESCRIPTION
**Pull request by JanStreffing**
Fixing https://github.com/esm-tools/esm_tools/issues/291

### CODE REVIEW

**Review by mandresm — APPROVED** [review]
I'll cherry-pick this into the `feature/awicm3` branch and add the changes also to the `AWICM3` runscripts.

**Comment by JanStreffing** [comment]
> I'll cherry-pick this into the `feature/awicm3` branch and add the changes also to the `AWICM3` runscripts.

For now our default experiment yaml files were using the default values from the component yaml files. So there was no need to change anything for awicm3. Though if one does want to customize the number of MPI tasks the have to do so with nproc instead of nproca now.

**Comment by JanStreffing** [comment]
> I'll cherry-pick this into the `feature/awicm3` branch and add the changes also to the `AWICM3` runscripts.

Can we also merge this here?

**Comment by mandresm** [comment]
> > I'll cherry-pick this into the `feature/awicm3` branch and add the changes also to the `AWICM3` runscripts.
> 
> Can we also merge this here?

Yes, I'm on it right now. Should we also merge to `geomar_awicm3`?

**Pull request merged**
