### PR TITLE
Adding new OASIS coupling method gauswgt_glo for awicm3.

### LINKED ISSUE #1068: Add new OASIS coupling method into the awicm3.yaml file
When dealing with an oasis issue that was causing the crash of the simulations few months ago, we thought that in the remapping of the heat fluxes is safer to use a different coupling method wrt the one we were previously using, i.e. globpos instead of gsspos.

it means that the following lines could be added in the oasis section of the runscript (to avoid modifying directly the awicm3.yaml file):

coupling_target_fields:
                rstas.nc:
                        - 'heat_oce:heat_swo <--gauswgt_gss-- A_Qns_oce:A_Qs_all'
                        - 'prec_oce:snow_oce:evap_oce:subl_oce <--gauswgt_gss-- A_Precip_liquid:A_Precip_solid:A_Evap:A_Subl'
                        - 'heat_ico <--gauswgt_glo-- A_Q_ice'
                        - 'taux_oce:tauy_oce:taux_ico:tauy_ico <--bicubic-- A_TauX_oce:A_TauY_oce:A_TauX_ice:A_TauY_ice'
                        - 'R_Runoff_atm:R_Calving_atm <--gauswgt_gss-- A_Runoff:A_Calving'
                        - 'hydr_oce:enth_oce <--gauswgt_gss-- R_Runoff_oce:R_Calving_oce'

to have 'heat_ico <--gauswgt_glo-- A_Q_ice' instead of 'heat_ico <--gauswgt_gss-- A_Q_ice'

with

                gauswgt_glo:
                        time_transformation: conserv
                        remapping:
                                gauswgt:
                                        search_bin: latitude
                                        nb_of_search_bins: 1
                                        nb_of_neighbours: 25
                                        weight: "0.1"
                        postprocessing:
                                conserv:
                                        method: global
                                        algorithm: opt

I added the new gauswgt_glo coupling method into the awicm3.yaml file in my esm_tools folder but it should maybe be added in the default version so that if someone else would also run the same configuration or a different one of Tco319-DART the runscript could anyhow find the new method in it?

I am adding also @JanStreffing that of course helped in locating and solving the issue.

### PR DESCRIPTION
**Pull request by nwieters**
Adding a new OASIS coupling method for awicm3.

closes #1068 

I only added the new coupling method but didn't change the default coupling method for `heat_ico` or any other coupling fields.

### CODE REVIEW

**Review by JanStreffing — APPROVED** [review]

**Comment by nwieters** [comment]
#approve_changes

**Comment by nwieters** [comment]
#approve-changes

**Comment by nwieters** [comment]
#bump

**Comment by nwieters** [comment]
#bump #patch

**Pull request merged**
