### PR TITLE
fix/import git in juwels

### PR DESCRIPTION
**Pull request by mandresm**
In Juwels, `import git` from the `helpers.py` results into an error stating that git needs to be loaded. This PR adds the `module load git` to the Juwels environments to solve the problem.

### CODE REVIEW

**Comment by pgierz** [comment]
That is also needed on Levante, I'll take care of it

**Comment by mandresm** [comment]
Interestingly enough, in Levante I had no problems to run the tests.

**Comment by pgierz** [comment]
Nevermind, already there

**Review by pgierz — APPROVED** [review]

**Comment by mandresm** [comment]
please, do not bump yet, I am still testing something

**Comment by pgierz** [comment]
OK. change from draft to real PR once you are ready to go :-)

**Comment by mandresm** [comment]
#bump

**Pull request merged**
