### PR TITLE
Mistral openmpi

### PR DESCRIPTION
**Pull request by mandresm**
Working `openMPI` environment for `AWICM3` on `mistral` (environment taken from the @hegish ksh environment).

If `useMPI` is not specified in the `runscript` or through the `esm_master` using the `-m` flag, everything remains as before.

### CODE REVIEW

**Review by JanStreffing — APPROVED** [review]
I figure this is tested, so I have no objections.

**Comment by JanStreffing** [comment]
> If `useMPI` is not specified in the `runscript` or through the `esm_master` using the `-m` flag, everything remains as before.

Btw: Is is possible to set a default esm_master env for a specific combination of machine and model?

**Comment by mandresm** [comment]
Yes, simply adding the following to the model yaml:
```
computer:
    choose_computer.name:
        mistral:
            useMPI: openmpi
```

**Comment by JanStreffing** [comment]
Ok good to know. I guess it more applies to HLRN where the MPI is not a free choice yet. For this PR on mistral everything looks good.

**Pull request merged**
