### PR TITLE
Prep release awicm3 geomar

### PR DESCRIPTION
**Pull request by mandresm**
Please, note that GitHub does not seem to handle very well the actual changes happening due to a merge, when this merge is very complicated. Therefore, looking at the `Files changed` is misleading. I will do the merge on the terminal using `git commands`. I'll be pointing at the conflicts here on GitHub if I don't know how they should be resolved.

### CODE REVIEW

**Comment by mandresm** [comment]
Just figured out we probably don't want to compare before we merge the `hist_fixed` branch, due to conflicts in `echam` files, so let's wait until that happens.

**Review by mandresm — COMMENTED** [review]
Even after having merged `hist_fixed` into `monorepo` (#496), there are substantial changes that this merge will introduce into the `echam`/`jsbach` files, that could potentially conflict with other groups running historical simulations with `echam`.

@seb-wahl , @denizural can you give a look to the following files? (I have not much experience with ECHAM):
- echam.yaml
- echam.datasets.yaml
- jsbach.datasets.yaml
- jsbach.yaml

**Comment by mandresm** [comment]
[ESM-132]

[ESM-132]: https://esm-tools.atlassian.net/browse/ESM-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pgierz** [comment]
Wasn't this "chunk parts" element fixed? I am a bit unhappy about the failing tests...

**Comment by mandresm** [comment]
That should be certainly work. I mean, I am running my tests in all computers right now, so I don't really get what's going on here.

**Comment by mandresm** [comment]
That message has happened before when any flavor of `prep_release` branch is tested in GitHub, as the installation installs the packages in `release` by default, and that gives the `chunky_parts` error.

Another error that we are experiencing in the CI since last friday is the failing installation of `esm_tools` that happens due to the missing `HISTORY.rst` file. You fixed that in your branch but is not yet in `monorepo` so I would not expect tests succeeding until we merge that.

**Comment by mandresm** [comment]
All tested and working (except `oifsamip` that is still WIP):

- awicm:                                                                                                                                                                                                                              [8/1837]
    - 2.0:
        - awicm2-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
    - CMIP6:
        - awicm1-CMIP6-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- awicm3:
    - frontiers:
        - awicm3-frontiers-TCO159L91-CORE2_initial:
            - juwels:   compiles        runs
            - mistral:  compiles        runs
            - ollie:    compiles        runs
    - v3.0:
        - awicm3-v3.0-TCO159L91-CORE2_initial:
            - juwels:   compiles        runs
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- awiesm:
    - 2.1-recom:
        - all_awiesm-2.1-recom:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
    - 2.1-wiso:
        - PI_ctrl_awiesm-2.1-wiso:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- echam:
    - 6.3.04p1:
        - echam6.3.04p1-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- fesom:
    - 2.0:
        - fesom2.0-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
    - 2.1:
        - fesom2.1-initial-monthly:
            - mistral:  compiles        runs
            - ollie:    compiles        runs
- fesom-recom:
    - 1.4:
        - fesom-recom1.4-initial-daily:
            - ollie:    compiles        runs
- foci:
    - default:
        - foci-initial-piCtl-test_daily_restart_lowcpu:
            - blogin:   compiles        runs
            - juwels:   compiles        runs
- focioifs:
    - 2.0:
        - focioifs-piCtl-test_lowcpu:
            - blogin:   compiles        runs
            - juwels:   compiles        runs
- oifs:
    - 43r3-v1:
        - oifs-43r3-tco95-amip-test_lowcpu:
            - blogin:   compiles        runs
            - juwels:   compiles        runs

**Pull request merged**
