### PR TITLE
Focioifs 2.0.1

### PR DESCRIPTION
**Pull request by joakimkjellsson**
I've made some slight changes to FOCI-OpenIFS. This works fine in ESM-Tools release 6, except for NEMO postprocessing, but I'll see to that later. 
Changes should not impact anything else except FOCI-OpenIFS.

### CODE REVIEW

**Comment by pgierz** [comment]
You will get a few failing checks, please ignore that.

**Review by mandresm — APPROVED** [review]
I also don't see any potential conflicts with the merging. I'll wait for @seb-wahl review though.

**Comment by joakimkjellsson** [comment]
Great. I'll wait for Sebastian's opinion too. I added a variable to "opac_fields" in NEMO, but it should not change FOCI at all. 
When the merge is done, feel free to remove the focioifs_2.0.1 branch.

**Review by seb-wahl — APPROVED** [review]
Just tested foci-default, still works. I was a bit worried about the `opa_c` changes, but they seem to be ok.

**Comment by mandresm** [comment]
Great then I'm going to merge it.

**Comment by mandresm** [comment]
#bump #patch

**Pull request merged**
