### PR TITLE
adding HR mesh for fesom2

### PR DESCRIPTION
**Pull request by JanStreffing**

### CODE REVIEW

**Comment by JanStreffing** [comment]
WIP Needs one more commit from Jian Shi.

**Comment by pgierz** [comment]
What is still required here? I'd also like to clarify if this is a new minor number (6.9 -> 9.10) or a new fix number (6.9.0 -> 6.9.1) That is actually a topic for larger discussion: when to bump which number. We aren't adding a new model or a new element of the run (post processing or plot or something) here, thus, in my book: no new feature. We are however allowing a new mesh for an existing model, so "kindof..?" new feature? Something to talk about...

**Comment by JanStreffing** [comment]
I can not remember. Maybe Jian Shi <jian.shi@awi.de> still knows?

**Comment by pgierz** [comment]
Is Jian on GitHub, or is an email better?

**Comment by shijian0702** [comment]
Hi Paul, Jan,

This should be a new fix number, only adding the fesom HR mesh in esm_tools/configs/components/fesom/fesom-2.0.yaml and the corresponding namelists: /home/a/a270196/esm_tools/namelists/fesom2/2.0/HR. 
By the way, how to merge these changes into the newest release? Now I have to add the HR mesh by hands if I want to use the 6.9.2 that awicm3.1 is available.

Jian

**Comment by pgierz** [comment]
Hi Jian, do you have any new commits that need to be added? If so, just make sure you are on this branch and do a `git push`; the commits will pop up here and one of us will add them to the main release branch. 

If you need any help with that feel free to stop by my office :-)

**Comment by JanStreffing** [comment]
I think this can be merged as is.

**Comment by pgierz** [comment]
OK.

@mandresm, I'll use god mode for this one.

#bump

**Pull request merged**
