### PR TITLE
Ci/automate esm tests info update

### PR DESCRIPTION
**Pull request by mandresm**
Should allow for approval of changes in the `esm_tests` info by typing `$approve-changes` command (change $ by #).

### CODE REVIEW

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
a comment

**Comment by mandresm** [comment]
a comment

**Review by denizural — COMMENTED** [review]
Commit command is commented out but I think you will open that later on.

**Comment by mandresm** [comment]
Hi @pgierz, this is not completed but I need to merge the current status to be able to continue with the development (as it is not commited to release, it cannot be triggered...)

**Comment by mandresm** [comment]
> Commit command is commented out but I think you will open that later on.

that's correct

**Comment by mandresm** [comment]
I'll be merging and then making a new PR again, since it touches no ESM-Tools functionality.

**Pull request merged**
