### PR TITLE
fix/albedo system libs

### PR DESCRIPTION
**Pull request by mandresm**
fix environment variables to use the system libs. Thanks to @sebhinck for spotting those!

### CODE REVIEW

**Review by pgierz — APPROVED** [review]
And now comes....version `6.20.1` ;-) Thanks @sebhinck

**Comment by pgierz** [comment]
Still need new changes in test "truth" to get passing CI. @mandresm, is the standard workflow for that documented somewhere and I am just too lazy to find it?

**Comment by mandresm** [comment]
> Still need new changes in test "truth" to get passing CI. @mandresm, is the standard workflow for that documented somewhere and I am just too lazy to find it?

https://esm-tools.readthedocs.io/en/latest/esm_tests.html#esm-tests-cookbook

**Comment by pgierz** [comment]
> > Still need new changes in test "truth" to get passing CI. @mandresm, is the standard workflow for that documented somewhere and I am just too lazy to find it?
> 
> https://esm-tools.readthedocs.io/en/latest/esm_tests.html#esm-tests-cookbook

🤦🏻 ...thanks

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#bump

**Pull request merged**
