### PR TITLE
remove stray macOS file system metadata file and add these files to gitignore

### PR DESCRIPTION
**Pull request by hegish**

### CODE REVIEW

**Comment by mandresm** [comment]
Thanks @hegish for this contribution. Isn't it necessary to also remove the .DS_Store file itself from the repository?

**Review by mandresm — APPROVED** [review]
Thanks @hegish for this contribution

**Comment by hegish** [comment]
Yes, the .DS_Store file is removed with this commit. There are two changed files.

**Comment by mandresm** [comment]
@hegish , I am preparing a hotfix branch for some of the things we talked about yesterday, therefore, I changed the target branch for this pull request to `hotfix/install`. This branch will be merge into release later.

**Pull request merged**
