### PR TITLE
Feat/awiesm 2.1 levante

### PR DESCRIPTION
**Pull request by khimstedt**
The changes are mainly related to the tracer loop parallelization of FESOM REcoM for awiesm 2.1 on Levante. Some of the changes may also be of more general relevance: E.g. workaround for hetjob blocks generation in runscript header, workaround for hetjob blocks generation for `srun` command, setting of OpenMP environment variables for appropriate pinning of threads, setting `--hint=nomultithread` option for `srun` command.

### CODE REVIEW

**Comment by pgierz** [comment]
@chrisdane can you test this from the user side in a clean install?

Edit: or recommend who in the recom group would be a good text candidate on the user side?

**Comment by chrisdane** [comment]
Probably @a270105 Ying

**Comment by a270105** [comment]
> Probably @a270105 Ying

yes, I am the one in the group running aaiesm-2.1-recom-par-tracers.

**Comment by mandresm** [comment]
I am going to be splitting this PR into two, one for the Levante fixes by @khimstedt, and this one will stay here as a draft for changes in awiesm-2.1-recom. After talking to @a270105 , she still needs to do quite some changes in this branch before it gets merged.

**Comment by mandresm** [comment]
This branch is deprecated and the changes needed by @a270105 are already all merged in `release` in #831. Is that correct Ying?

**Comment by a270105** [comment]
yes

**Pull request closed without merging**
