### PR TITLE
latest developments from geomar branch

### PR DESCRIPTION
**Pull request by seb-wahl**

### CODE REVIEW

**Comment by seb-wahl** [comment]
I solved two merge conflicts already, so no more conflicts

**Comment by seb-wahl** [comment]
I hope it was the correct way to do it as I just figured that this merge already merged all the monorepo stuff into my branch.

**Review by pgierz — APPROVED** [review]
Seems good to me. @seb-wahl, do you want to add some sort of auto-tests to FOCI? We could for instance by default check compilation on the AWI HPC, and that already catches at least some basics of the YAML.

**Comment by seb-wahl** [comment]
Yes that would be nice. Curious to see if FOCI compiles directly with your default `ollie.yaml`. Depending on how the NETCDF modules are build on your machine it will work out of the box. As you know we use our home-made libs on all HPCs so that we only need intel and intelmpi as modules. Let me know if you need further input. But we can also leave that for release 6.1

**Review by mandresm — APPROVED** [review]

**Comment by mandresm** [comment]
I don't foresee any conflicts with other models so I am going to merge it now, and send all the tests later on.

**Pull request merged**
