### PR TITLE
Feat/awiesm pism

### PR DESCRIPTION
**Pull request by mandresm**
Add the work by @ackerlar and @khimstedt on PISM and Icebergs.

**TODO**

- [x] @ackerlar test whether his setup works with version 6 before generalization and preparation for merge
- [ ] Generalize `esm_runscripts` mods
- [ ] Look at this comments and take action: https://github.com/esm-tools/esm_runscripts/pull/193#discussion_r749233806
- [ ] Generalize yamls to avoid confligs
- [ ] General compatibility testing with other models and computers

### CODE REVIEW

**Comment by pgierz** [comment]
Please ignore the failing checks! Something is misconfigured on the custom GitHub runner we have on AWI's HPC system, I am looking at that over the next few hours.

**Comment by mandresm** [comment]
Hi @ackerlar ,

I've done the merging in `esm_runscripts`. Let's work from now on on this branch :)

Can you please test whether your setup is working now on version 6, in the `feat/awiesm-pism` branch, after this changes?

**Comment by ackerlar** [comment]
I tested and had to made some changes that didn't make it into the latest esm_tools update regarding the awiesm-pism coupling. I pushed them to [https://github.com/esm-tools/esm_tools/tree/feat/awiesm-pism](url)

**Comment by mandresm** [comment]
Thanks @ackerlar ! 

If everything is working for you then that means we can move on into the next step, which will be to cleanup the modifications in `esm_runscripts`. Can you provide the runscrips for a small simulation and instructions on how to install and run your setup? Then we can do testing as we make the changes.

**Comment by ackerlar** [comment]
@mandresm I just found that the model crashed after some years... But this could also be related to the latest FESOM version I am using. Will do another test and give a working example once I am sure about the issue.

**Comment by ackerlar** [comment]
The issues was not related to the esm_tools itself or FESOM. I got mixed up with the fesom mesh rotation in the script that generates the icebergs. I changed this and added a working example in `esm_tools/runscripts/awicm-pism`
To run the setup, you have to:
- install `esm_tools` version 6 `feat/awiesm-pism` branch
- install `awiesm-2.1` and switch to the ECHAM branch `ice-addhosing` and FESOM branch `paleodyn/awiesm-2.1-gamma`
- install PISM `pism-github1.2.1` (this does not work for me through `esm_tools` though. I used the version, I installed manually)
- adapt the paths (`base_dir`, `model_dir`,`script_dir`) and `account` in `esm_tools/runscripts/awicm-pism/awiesm.yaml`, `esm_tools/runscripts/awicm-pism/pism.yaml` and `esm_tools/runscripts/awicm-pism/awiesm_pism.yaml`
- run `esm_runscripts awiesm_pism.yaml`

**Comment by pgierz** [comment]
On my list of tasks, then:

+ [ ] Create a `paleodyn/awiesm-2.1-gamma` also for ECHAM, I find that to be a cleaner solution, and we can make a unified code-base finally for all little bits and pieces of the model. Of course, you can still have your own unique branch, but at least (IMHO) it would be good to have awiesm-gamma at some point all come out of the same box. (Perhaps of interest for @mwerner-awi and @xshi-awi)
+ [x] Check why PISM doesn't install for you. The checks are passing on release of esm-tools, see here: https://github.com/esm-tools/esm_tools/runs/4894002359?check_suite_focus=true

**Comment by pgierz** [comment]
And, totally random aside note: Why do I put (and recommend others) to put `/` in the branch names? That makes git behave more like a directory structure on linux. You can then have a "folder" for fixes, a "folder" for features, and (in our case) a "folder" for paleodyn model changes.

**Comment by mandresm** [comment]
> * Check why PISM doesn't install for you. The checks are passing on release of esm-tools, see here: https://github.com/esm-tools/esm_tools/runs/4894002359?check_suite_focus=true

I can take care of looking at this. I had to work myself through this for release 6. Also, during release 6 I managed to make a "fake" setup that installs vilma-pism with one single esm_master line. I could look into that as well for awiesm-2.1-pism, just let me know if you guys agree with this, and I can work it out.

**Comment by ackerlar** [comment]
I found a silly error in `esm_tools/configs/components/pism/pism.compiletime_env_changes.yaml` that only came into place on mistral. I pushed the changes. Now, the compiling goes further but still does not finish.

Edit: I try to install pism on mistral. The tests are done on ollie, though, aren't they?

**Comment by pgierz** [comment]
I also just checked by hand on the auto-erasing dummy account of ollie. `pism-github1.2.1` compiles file. No idea about running the model. ~But if I remember correctly @ackerlar was using mistral and not ollie, so I do not know about that.~ Edit: sorry, I should have refreshed the page, Lars just clarified that.

And, can I just say how happy I am about all these little green check marks we see in the checks? They make me sleep better at night. If we can build out and configuring that cleverly I think it would save many many headaches down the line.

**Comment by mandresm** [comment]
> And, can I just say how happy I am about all these little green check marks we see in the checks? They make me sleep better at night. If we can build out and configuring that cleverly I think it would save many many headaches down the line.

It is indeed amazing ;)

**Comment by mandresm** [comment]
> I found a silly error in `esm_tools/configs/components/pism/pism.compiletime_env_changes.yaml` that only came into place on mistral. I pushed the changes. Now, the compiling goes further but still does not finish.
> 
> Edit: I try to install pism on mistral. The tests are done on ollie, though, aren't they?

I am facing a compilation issue too. I just realized I've never compiled PISM in mistral. If your manual compilation is working, then I suggest you compare the `comp-pism*.sh` file against the environment you are using for your manual compilation.

The error for me looks like this:
```cd /work/ab0995/a270152/model_codes/pism-github1.2.1/build/src/util && /sw/rhel6-x64/intel/impi/2018.5.288/compilers_and_libraries/linux/mpi/bin64/mpiicpc   -I/sw/rhel6-x64/netcdf/netcdf_c-4.3.2-parallel-impi-intel14/include -I/sw/rhel6-x64/util/udunits-2.2.26-gcc64/include -I/sw/rhel6-x64/numerics/fftw-3.3.7-openmp-gcc64/include -I/sw/rhel6-x64/numerics/PETSc-3.12.2-impi2018-intel18/include -I/work/ab0995/a270152/model_codes/pism-github1.2.1/build  -std=c++11 -O3 -fp-model precise -no-fast-transcendentals -march=native -O2 -g -DNDEBUG   -fPIC -std=c++11 -o CMakeFiles/util.dir/petscwrappers/IS.cc.o -c /work/ab0995/a270152/model_codes/pism-github1.2.1/src/util/petscwrappers/IS.cc
/work/ab0995/a270152/model_codes/pism-github1.2.1/src/util/io/NC3File.cc(888): error: identifier "NC_FORMAT_64BIT_OFFSET" is undefined
    case NC_FORMAT_64BIT_OFFSET:
         ^

/work/ab0995/a270152/model_codes/pism-github1.2.1/src/util/io/NC3File.cc(890): error: identifier "NC_FORMAT_64BIT_DATA" is undefined
    case NC_FORMAT_64BIT_DATA:
         ^
```

I think `NC_FORMAT_64BIT_DATA` is a subroutine from netcdf so the netcdf might be a good place to start looking at.

**Comment by ackerlar** [comment]
It finally works! I guess it makes sense to put everything into an `awiesm-2.2` setup, like you mentioned before @mandresm (with `awiesm-2.1-pism`). What do you think?

**Comment by mandresm** [comment]
> It finally works! I guess it makes sense to put everything into an `awiesm-2.2` setup, like you mentioned before @mandresm (with `awiesm-2.1-pism`). What do you think?

Do you mean to be able to compile everything just with `esm_master install-awiesm-2.2`?

And I have a question about the name, does `awiesm-2.2` means that there is pism included, while 2.1 is without pism?

**Comment by ackerlar** [comment]
@mandresm Sorry for the confusion. I compiled `awiesm-2.1` and `pism` separately but with `esm_master`, though. I used:
`esm_master comp-awiesm-2.1` and
`esm_master comp-pism-github1.2.1`

I think `awiesm-2.2` would be `awiesm-2.1` + `pism`. At least, that was the case for `awiesm-1.2` and that is, what I understand from `configs/setups/awiesm/awiesm-2.2.yaml` that is already included in the esm_tools. @pgierz please correct me if I am wrong.

**Comment by pgierz** [comment]
Yes, correct. The AWIESM naming zoo is confusing to most people, so, we have:

1.1 --> ECHAM plus FESOM 1.4
1.2 --> 1.1 plus PISM

2.x as with 1.x, but fesom 2 instead. The idea was to separate a bit enabled features into the second version number and enabled settings into the variant (alpha, beta, gamma) and that somehow follows the idea behind semantic versioning, but it got a bit messy. wiso is, for example, also a few feature, but didn't create a new version number. I suppose this is sort of the expected outcome when scientists do some kinda/sorta/close-enough version software engineering ;-)

**Comment by pgierz** [comment]
And, @ackerlar a very very big thumbs up for getting pism to build on mistral. I have sat in front of enough compiling screens to know how annoying that is.

**Comment by mandresm** [comment]
If that's the case, why don't we use `awicm-2.2.yaml` to expand `awicm-2.1.yaml` instead of building it up from the beginning? This would mean that we only maintain one main AWIESM2 file, and that new implementations in `awicm-2.1.yaml` will be relatively easy to transfer or made automatically compatible with `awiesm-2.2`. There are a number of ways we could do that: one is to use a `further_reading` on `awiesm-2.2.yaml` to include `awiesm-2.1.yaml` (kind of a mess). The other possibility is the opposite direction: to prepare an `awiesm-2.2.yaml` extension that then it is attach to `awiesm-2.1.yaml` using a `further_reading` under a version `choose_`, in my opinion the best option.

**Comment by ackerlar** [comment]
@pgierz Thanks! I am happy that it went quite smoothly today.
@mandresm i think I cannot say too much about this but expanding the existing `awiesm-2.1.yaml` sounds very reasonable to me.

A bit of a side question here: Are the `awiCM` settings used? The only difference to `awiesm` is the dynamic vegetation, isn't it?

**Comment by mandresm** [comment]
> A bit of a side question here: Are the `awiCM` settings used? The only difference to `awiesm` is the dynamic vegetation, isn't it?

I don't know, I've never really done a diff in between the two. I also don't know why they were split on the first place.

**Comment by pgierz** [comment]
I just merged in lars' work here, so we are one step closer to a consolidated AWIESM. There are still a few things I'd like to look at:

* WISO compatibility
* Namelists need to match up with alpha/beta/gamma. (Some users have had problems with `k_gm` and `k_gm_max`

In the end, I'd like to just have one single AWIESM yaml where you can selective turn on and off any "extra" feature: wiso, pico, icebergs, and also switch between alpha, beta, and gamma.

On top of that, we should have only one branch for each model component, where you can selectively turn on or off various parts with namelist switches. For FESOM that is already there (at least, no one complained yet). For ECHAM I will try to put everything together later this week.

**Comment by pgierz** [comment]
I'm going to close this and re-open a separate one for pism integration once we finish cleaning up.

**Pull request closed without merging**
