### PR TITLE
Hotfix/echam standalone runscripts

### PR DESCRIPTION
**Pull request by mandresm**
Added yaml runscripts for echam standalone in mistral both for cold start and restart and fixed a number of issues related to the restart of `echam`, mostly for `jsbach` and `hdmodel`:

- Fixes in `jsbach.yaml`, `hdmodel.yaml`, `jsbach.inherit.yaml`, `hdmodel.inherit.yaml` for allowing restarting from another experiment with different experiment id. 

- `hdmodel` copies now the restarts into the general experiment folder inside `<base_dir>/<experiment_id>/restart/hdmodel/` with a name that includes date and time. Before it was copying them to `<base_dir>/<experiment_id>/restart/hdmodel/<parent_expid>/run_YYYYMMDD-YYYYMMDD/work/` which was likely a mistake.

- Other little changes.

This hotfix addresses most of the issues in #77.

### CODE REVIEW

**Comment by SpontEIN** [comment]
I checked out the hotfix an tried to run `echam-mistral-restart-monthly.yaml`.

The restart files in `/work/ab0246/a270152/default/echam_pictrl_monthly/restart/echam/` can not be accessed by my account: `Permission denied`

**Comment by mandresm** [comment]
Can you check if now works?

**Comment by SpontEIN** [comment]
> Can you check if now works?

nope still not:
`drwxr-s---   5 a270152 ab0246  4096 Aug 18 10:29 a270152`

**Comment by SpontEIN** [comment]
> Can you check if now works?

nope still not:
`drwxr-s---   5 a270152 ab0246  4096 Aug 18 10:29 a270152`

**Comment by mandresm** [comment]
Is it working now?

**Comment by SpontEIN** [comment]
> Is it working now?

hmm, no still not:
`ll /work/ab0246` still yields that the work dir is not readable by `others`

**Comment by SpontEIN** [comment]
yes the dir is now accessible.
However the run ist still missing jsbach restart files. The files seem to be the available in your work dir, but it is looking for them in my work dir. Am I doing something wrong?
```
========================================================
MISSING FILES:
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_jsbach.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/jsbach//restart_echam_test_20000229235230_jsbach.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_jsbid.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/jsbach//restart_echam_test_20000229235230_jsbid.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_yasso.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/jsbach//restart_echam_test_20000229235230_yasso.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_surf.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/jsbach//restart_echam_test_20000229235230_surf.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_nitro.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/jsbach//restart_echam_test_20000229235230_nitro.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_veg.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/jsbach//restart_echam_test_20000229235230_veg.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_land.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/jsbach//restart_echam_test_20000229235230_land.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/hdmodel//hdrestart.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/restart/hdmodel//restart_echam_test_20000229235230_hdrestart.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//restart_echam_test_jsbach.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_jsbach.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//restart_echam_test_jsbid.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_jsbid.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//restart_echam_test_yasso.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_yasso.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//restart_echam_test_surf.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_surf.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//restart_echam_test_nitro.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_nitro.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//restart_echam_test_veg.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_veg.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//restart_echam_test_land.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/jsbach//restart_echam_test_land.nc
--  /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/work//hdrestart.nc: 
        --> /work/aa0238/a270119/esm-experiments//echam_test/run_20000301-20000331/restart/hdmodel//hdrestart.nc
========================================================

```

**Comment by mandresm** [comment]
As a provisional solution please try `git checkout 6f3350f286c702a796450bde0d0776a63e8ee961` in `esm_tools`.

**Comment by SpontEIN** [comment]
> As a provisional solution please try `git checkout 6f3350f286c702a796450bde0d0776a63e8ee961` in `esm_tools`.

The missing files remain ... is a `git checkout <some-commit>` enough to revert to that commit or do I need to do something additionally?

So the problem seems to be, that jsbach AND hdmodel look for restart files in my `base_dir` and in this run specific subfolder (e.g. `run_20000301-20000331/`). Unless they have been copied there before, this can not work.

The directories are:

- `<base_dir>/<exp_id>/restart/jsbach/`
- `<base_dir>/<exp_id>/restart/hdmodel/`
- `<base_dir>/<exp_id>/run_20000301-20000331/restart/jsbach/`
- `<base_dir>/<exp_id>/run_20000301-20000331/restart/hdmodel/`

**Comment by mandresm** [comment]
I have faced this problem too, and it is solved in `esm_runscripts` /esm-tools/esm_runscripts#22. Ill be merging all these fixes to release tomorrow morning and then it should all work.

**Pull request closed without merging**
