### PR TITLE
Docs: update uninstall instructions

### LINKED ISSUE #817: documentation for unistall is out of date
`esm_versions upgrade esm_parser`

`esm_versions` no longer exists

### PR DESCRIPTION
**Pull request by pgierz**
Updates the uninstall info. Closes #817 

@JanStreffing if this is to your liking, go ahead and merge. No bump is needed for a docs update.

### CODE REVIEW

**Review by JanStreffing — APPROVED** [review]

**Comment by pgierz** [comment]
Maybe I pushed the button too early: I actually do not know if RTD builds correctly, I think @mandresm mentioned at some point that something was currently misbehaving, but that is for another time…

**Comment by JanStreffing** [comment]
You can revert and add the branch as a build target on RTD to try out if the branch builds.

**Comment by pgierz** [comment]
Nevermind, it looks like it is good online as well. I just hope that no one freaks out at my uninstall pipe xargs magic 🤞🏻

**Comment by pgierz** [comment]
@mandresm: can we update the `esm-Tests` truth to get passing tests? I only changed a rst file, that should not have induced breaking tests 🤣

**Comment by denizural** [comment]
@pgierz I have the fixes for docs not building. I will push them.

**Comment by pgierz** [comment]
@denizural please make a PR for that. As I mentioned, my changes popped up fine, so I am not sure what is breaking. It was from my side anyway just a vague memory which may have since then been fixed already.

**Comment by pgierz** [comment]
And according to the docs build page here: https://readthedocs.org/projects/esm-tools/builds/

Everything seems to be groovy. So, sorry from my side for the false alarm.

**Comment by mandresm** [comment]
Sorry for the delay with `esm_tests`. I'll get them fix today.

**Pull request merged**
