### PR TITLE
Hotfix/fesom yearnew branchoff

### PR DESCRIPTION
**Pull request by mandresm**
Fixes for restarting fesom as a branchoff experiment. When branching off `yearnew` in the `namelist.config` cannot be equal to the last number in the `fesom.clock`, otherwise it ignores the fesom restart files and does a spinup.

### CODE REVIEW

**Comment by mandresm** [comment]
This is merged already for the AWICM3 branches.

Once approved needs to be merged in the following branches:

- [x] wiso
- [x] awiesm-wiso-recom
- [x] prep_release

**Review by dbarbi — CHANGES_REQUESTED** [review]
Is the actual change in the clock_init missing for fesom-2.1?

**Comment by mandresm** [comment]
> Is the actual change in the clock_init missing for fesom-2.1?

Do you mean these lines? 

https://github.com/esm-tools/esm_tools/blob/fb10646f4d1c273d73ed556253233e4e45e24105/configs/components/fesom/fesom-2.1.yaml#L203-L213

**Review by dbarbi — APPROVED** [review]

**Comment by mandresm** [comment]
I'll bumpversion and merge it now.

**Pull request merged**
