### PR TITLE
better error message in case of missing model folder

### PR DESCRIPTION
**Pull request by JanStreffing**

### CODE REVIEW

**Comment by JanStreffing** [comment]
Some changes on blogin from foci. Maybe the test script needs updating of the correct state here?

**Review by pgierz — APPROVED** [review]

**Comment by pgierz** [comment]
I use neither foci nor the blogin computer, so I can't comment on that ;-)

**Comment by mandresm** [comment]
There is a silly issue with `esm_tests` affecting exclusively to FOCI. So you can ignore the error here. I'll be fixing that issue later today or next week.

**Comment by mandresm** [comment]
#bump

**Pull request merged**
