### PR TITLE
Fix/awi libs and project juwels

### LINKED ISSUE #593: Problem on AWICM3 installation on JUWELS
Hi all,

I have some problems when installing AWICM3 on JUWELS, which I think may be related to the netcdf-Fortran configuration.
I will be grateful if anyone can have a look at it. By the way, this issue cannot be reproduced in other HPCs, like ollie, mistral.

Best,
Jian

**System**
 - Supercomputer: JUWELS (Stages 2022, Python/3.9.6, netCDF-Fortran/4.5.3-serial)
 - ESM-Tools 6.1**
 
I used the command: **esm_master install-awicm3-deck**, and it shows errors after asking for permission of all the components: 
(I also alter different stages, python, netcdf versions, but the same errors remain)

-- setting default build type: Release
-- The C compiler identification is Intel 2021.4.0.20210910
-- The CXX compiler identification is Intel 2021.4.0.20210910
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /p/software/juwels/stages/2022/software/OpenMPI/4.1.2-intel-compilers-2021.4.0/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /p/software/juwels/stages/2022/software/OpenMPI/4.1.2-intel-compilers-2021.4.0/bin/mpic++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is Intel 2021.4.0.20210910
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /p/software/juwels/stages/2022/software/OpenMPI/4.1.2-intel-compilers-2021.4.0/bin/mpifort - skipped
-- Checking whether /p/software/juwels/stages/2022/software/OpenMPI/4.1.2-intel-compilers-2021.4.0/bin/mpifort supports Fortran 90
-- Checking whether /p/software/juwels/stages/2022/software/OpenMPI/4.1.2-intel-compilers-2021.4.0/bin/mpifort supports Fortran 90 - yes
-- Looking for Fortran NCCRE
-- Looking for Fortran NCCRE - not found
-- Looking for nc__create
-- Looking for nc__create - not found
-- Configuring done
**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.**
Please set them or make sure they are set and tested correctly in the CMake files:
/p/home/jusers/shi4/juwels/model_codes/awicm3-deck/oasis/lib/psmile/NETCDF_Fortran_INCLUDE_DIRECTORIES
   used as include directory in directory /p/home/jusers/shi4/juwels/model_codes/awicm3-deck/oasis/lib/psmile
/p/home/jusers/shi4/juwels/model_codes/awicm3-deck/oasis/lib/scrip/src/NETCDF_Fortran_INCLUDE_DIRECTORIES
   used as include directory in directory /p/home/jusers/shi4/juwels/model_codes/awicm3-deck/oasis/lib/scrip/src
NETCDF_Fortran_LIBRARIES
    linked by target "psmile" in directory /p/home/jusers/shi4/juwels/model_codes/awicm3-deck/oasis/lib/psmile

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "/p/home/jusers/shi4/juwels/.local/bin/esm_master", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_master')())
  File "/p/home/jusers/shi4/juwels/esm_tools/src/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/p/home/jusers/shi4/juwels/esm_tools/src/esm_master/esm_master.py", line 106, in main_flow
    user_task.execute(ignore_errors)  # env)
  File "/p/home/jusers/shi4/juwels/esm_tools/src/esm_master/task.py", line 494, in execute
    subprocess.run(
  File "/p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./comp-oasis3mct-4.0-oifsdeck_script.sh']' returned non-zero exit status 1.

**Loaded modules**
image

### PR DESCRIPTION
**Pull request by JanStreffing**
The following branch will allow members of not only chhb19 but also chhb20 and chhb21 to use ideally configured Libraries on Juwels. fixes #593

### CODE REVIEW

**Comment by mandresm** [comment]
Does this work?

**Comment by pgierz** [comment]
Emm why am I assigned to this? I never work on Juwels so I cannot even test this. Sorry.

**Comment by mandresm** [comment]
@seb-wahl , I cleaned the IO libraries so that there is not repetition. Please, would you run a FOCI test in Juwels so we are sure I did not break anything for you?

**Comment by mandresm** [comment]
Problems during run time due to the missing cdo. Working on a solution and testing.

**Comment by JanStreffing** [comment]
Mhm I copied the cdo binary into the IO_LIB_ROOT/bin dir. Seems not to have worked.
We can try loading the cdo module maybe?

**Comment by mandresm** [comment]
I'm running tests with `module load CDO/2.0.2 in the exp environment

**Review by seb-wahl — APPROVED** [review]
I added the PSMIPFLAGS env var that we need for the compilation of ECHAM6 in Stage/2022 with ParaStationMPI went missing

**Comment by mandresm** [comment]
Sorry about that @seb-wahl , I'll give it another good review before merging this into release. But first, AWICM3 tests have to run successfully.

**Comment by seb-wahl** [comment]
In "my" `IO_LIB_ROOT` I have cdo that is compiled within the same environment, so its always in the path. Maybe @JanStreffing removed when he build the awi_libs based on my script to compile the libraries. I know that most centres have cdo as a module but with my approach we only depend on Intel and a MPI version from the machine.

**Comment by JanStreffing** [comment]
I use my own scripts that i distribute without the lib source code. So I never added it. Perhaps I should. But also using CDO module should work. There was only one stage on juwels that had no working cdo in the past.

**Comment by mandresm** [comment]
Adding `module load CDO/2.0.2` does not solve the problem. We can either put the `miniconda3` back into the `PATH` variable or add cdo to the awi_libs?

**Comment by JanStreffing** [comment]
Can you send me the path?

**Comment by mandresm** [comment]
/p/scratch/chhb19/mandresm/testing/run/awicm3/awicm3-v3.0-TCO159L91-CORE2_initial/

**Comment by JanStreffing** [comment]
Does the .env file still exist in esm_tools release 6? I think it's required for the shell scripts that prepare our input data and I can't find it anywhere under that path.

**Comment by mandresm** [comment]
Hi Jan, do you mean `env.sh`? It does still exist. For each run you can find it in `run_<DATE>/scripts`

**Comment by JanStreffing** [comment]
I don't think missing cdo is the problem here:` /p/scratch/chhb19/mandresm/testing/run/awicm3/awicm3-v3.0-TCO159L91-CORE2_initial/run_20000101-20000101/log/awicm3-v3.0-TCO159L91-CORE2_initial_awicm3_compute_5150980.log` readis:
```
cdo    seltimestep (Warning): Timestep 22 not found!

cdo    seltimestep (Abort): No timesteps selected!
sh: ncwa: command not found
```

**Comment by JanStreffing** [comment]
This comes from: 
https://github.com/esm-tools/esm_tools/blob/release/src/esm_runscripts/oasis.py#L493-L497

Either the problem is missing [ncwa](https://linux.die.net/man/1/ncwa) or time should be 12, not 22. Likely the former.
```

cdo sinfo /p/scratch/chhb19/mandresm/testing/run/awicm3/awicm3-v3.0-TCO159L91-CORE2_initial/run_20000101-20000101/work/heat_oce_fesom_01.nc
   File format : NetCDF
    -1 : Institut Source   T Steptype Levels Num    Points Num Dtype : Parameter ID
     1 : unknown  unknown  v instant       1   1    126858   1  F64  : -1            
   Grid coordinates :
     1 : generic                  : points=126858 (126858x1)
   Vertical coordinates :
     1 : surface                  : levels=1
   Time coordinate :
                             time : 12 steps
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
  0000-00-00 00:00:00  0000-00-00 00:00:00  0000-00-00 00:00:00  0000-00-00 00:00:00
  0000-00-00 00:00:00  0000-00-00 00:00:00  0000-00-00 00:00:00  0000-00-00 00:00:00
  0000-00-00 00:00:00  0000-00-00 00:00:00  0000-00-00 00:00:00  0000-00-00 00:00:00
cdo    sinfo: Processed 1 variable over 12 timesteps [0.06s 34MB].
```

**Comment by JanStreffing** [comment]
We should try to load NCO/5.0.3

**Comment by mandresm** [comment]
I am still find a problem when I include NCO:

```
===========================================================================================
::: Executing the step:  initialize_experiment_logfile    (step [4/6] of the job:  prepexp)
===========================================================================================

cdo    seltimestep (Warning): Timestep 22 not found!

cdo    seltimestep (Abort): No timesteps selected!
ncwa: ERROR file onlyonetimestep.nc not found. It does not exist on the local filesystem, nor does it match remote filename patterns (e.g., http://foo or foo.bar.edu:file).
ncwa: HINT file-not-found errors usually arise from filename typos, incorrect paths, missing files, or capricious gods. Please verify spelling and location of requested file. If the file resides on a High Performance Storage System (HPSS) accessible via the 'hsi' command, then add the --hpss option and re-try command.
cdo    seltimestep (Warning): Timestep 22 not found!

cdo    seltimestep (Abort): No timesteps selected!
ncwa: ERROR file onlyonetimestep.nc not found. It does not exist on the local filesystem, nor does it match remote filename patterns (e.g., http://foo or foo.bar.edu:file).
ncwa: HINT file-not-found errors usually arise from filename typos, incorrect paths, missing files, or capricious gods. Please verify spelling and location of requested file. If the file resides on a High Performance Storage System (HPSS) accessible via the 'hsi' command, then add the --hpss option and re-try command.
cdo    seltimestep (Warning): Timestep 22 not found!

cdo    seltimestep (Abort): No timesteps selected!
ncwa: ERROR file onlyonetimestep.nc not found. It does not exist on the local filesystem, nor does it match remote filename patterns (e.g., http://foo or foo.bar.edu:file).
ncwa: HINT file-not-found errors usually arise from filename typos, incorrect paths, missing files, or capricious gods. Please verify spelling and location of requested file. If the file resides on a High Performance Storage System (HPSS) accessible via the 'hsi' command, then add the --hpss option and re-try command.
cdo    seltimestep (Warning): Timestep 22 not found!
```
I'll have a look at it later on the day.

**Comment by JanStreffing** [comment]
I i gather that indeed we need NCO.
But apparently this not the only error. The timestep is also wrong.

**Comment by mandresm** [comment]
I think I found the problem. Finding the last time step is done in line: https://github.com/esm-tools/esm_tools/blob/722809ae508191222d674e658b6970f4f727a31c/src/esm_runscripts/oasis.py#L470

Runninf both in Juwels and Ollie the following command `cdo showtime A_Qns_oce_oifs_01.nc` yields in both cases:
```
 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00
cdo showtime: Processed 1 variable over 12 timesteps [0.01s 14MB]
```
However, if I add the `wc -w` (word count) in Ollie it counts only the first line of `00:00:00` yielding 12, while in Juwels it counts all the words in all the lines yielding 22.

I'm adding a solution to that.

**Comment by JanStreffing** [comment]
what the heck... different behavior of word count... well that's a new one. Good find!

**Comment by mandresm** [comment]
All tests in Juwels passed by now. I'll merge now. #bump

**Comment by JanStreffing** [comment]
Thanks a lot!

**Pull request merged**
