### PR TITLE
removed unneeded temporary namelist.echam files

### PR DESCRIPTION
**Pull request by chrisdane**
ps: `flake8 esm_tools` gives a lot of errors like
```
esm_tools/setup.py:5:1: F401 'setuptools.find_packages' imported but unused
esm_tools/setup.py:19:80: E501 line too long (85 > 79 characters)
```

### CODE REVIEW

**Review by pgierz — APPROVED** [review]

**Comment by pgierz** [comment]
Flake8 is badly configured for our project, and we don't really have a set code style. We should probably at some point start using one, and I think I always try to put my stuff through one of Python's auto-code formatters (black, in particular). Between release 6 and 7 we wanted to focus more on internal cleanup.

@mandresm can you do the whole tag/patch into develop/etc stuff? Maybe we can also add that whole process to the contributing guide so Chris can do it himself next time.

**Comment by pgierz** [comment]
.....wait, Chris, you are allowed to merge?

**Comment by chrisdane** [comment]
öh ups sorry i dont know o_O

**Comment by mandresm** [comment]
I think he is allowed to merge because you approved the PR and he has `write` permisions. Otherwise he would need admin permissions. But anyway, I agree, merges to `release` and `develop` should be banned from anyone that is not admin.

**Comment by pgierz** [comment]
I'll have a look at the settings, that should be possible to configure

**Comment by mandresm** [comment]
Bumversion is done, as well as merging into `develop` and `prep_release`

**Pull request merged**
