### PR TITLE
fesom branch changed

### PR DESCRIPTION
**Pull request by a270105**
fesom branch for awiesm-2.1-recom changed.

### CODE REVIEW

**Review by pgierz — APPROVED** [review]

**Comment by pgierz** [comment]
Will this be the final recom branch?

**Comment by mandresm** [comment]
I think this is the FESOM2-RECOM development branch.

**Comment by mandresm** [comment]
#bump

**Comment by a270105** [comment]
> I think this is the FESOM2-RECOM development branch.

Sorry that I need to get used to reply here...Yes, this is the branch where Martin and I update our fesom2-recom code. But Kai's tracer parallelization is not yet included.

**Pull request merged**
