### PR TITLE
fix for the new nemo version coupling

### PR DESCRIPTION
**Pull request by mandresm**
Fixes the bugs in `esm_master` introduce in #599

### CODE REVIEW

**Comment by pgierz** [comment]
Is this what I just emailed Laura about?

**Comment by mandresm** [comment]
I guess, everyone is having problems apparently... I'm also getting a bunch of emails

**Review by seb-wahl — APPROVED** [review]

**Comment by seb-wahl** [comment]
I don't understand why a merge broke this since it worked for me. Maybe some merge magic overwrote things the way it shouldn't. And the basic test the automatic tests do should have caught this I think.

**Comment by pgierz** [comment]
#bump

**Review by pgierz — APPROVED** [review]

**Pull request merged**
