### PR TITLE
fix/resolve early further_reading and version copy from general to steup

### PR DESCRIPTION
**Pull request by mandresm**
Resolve early further reading and copy/check the version between general and setup in early stages

### CODE REVIEW

**Comment by mandresm** [comment]
Tests are going to be failing, because something in esm_tests needs to be fixed

**Review by nwieters — APPROVED** [review]

**Comment by nwieters** [comment]
closes #1085

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#approve-changes

**Comment by mandresm** [comment]
#bump

**Pull request merged**
